import {authApi,dataApi,mikrotikApi,stateApi} from './src/api.js';
import {clone,mergedClients,normalized,text} from './src/model.js';
import {assignmentMap,connectionMapStatus,createNetworkMap,ctoPortSummary,findViability,geocodeAddress,networkCtos,networkMapState,networkNodes,networkOutageAlerts,networkSegments,parsePortList,servicePoints} from './src/network-map.js';

const $=(selector)=>document.querySelector(selector);
const esc=(value)=>String(value??'').replace(/[&<>"']/g,(c)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const finite=(value)=>Number.isFinite(Number(value))?Number(value):null;
const now=()=>new Date().toISOString();

let user=null,state={},stamp='',remoteClients=[],routers=[],clients=[],contracts=[],liveByKey=new Map(),map=null,liveBusy=false,liveTimer=null,drawing=false,draftPoints=[],viabilityPoint=null,fitDone=false,infrastructureDragging=false;

function canUseNetwork(){return String(user?.role||'').toLowerCase()==='admin'||(Array.isArray(user?.permissions)&&user.permissions.includes('network'));}
function toast(message,kind='success'){const root=$('#map-toast-root'),node=document.createElement('div');node.className=`map-toast${kind==='error'?' error':''}`;node.textContent=message;root?.append(node);setTimeout(()=>node.remove(),5000);}
function modal(title,body){const root=$('#map-modal-root');if(!root)return;root.innerHTML=`<div class="map-modal-backdrop" data-map-close-backdrop><section class="map-modal" role="dialog" aria-modal="true"><header><h3>${esc(title)}</h3><button class="modal-x" type="button" data-map-close>×</button></header><div class="map-modal-body">${body}</div></section></div>`;}
function closeModal(){const root=$('#map-modal-root');if(root)root.innerHTML='';}
function audit(next,action,entity,id,description=''){next.audit=[{id:crypto.randomUUID(),action,entity,entity_id:id??null,description,created_at:now(),created_by_id:user?.id||null,created_by_name:user?.name||user?.email||'Mapa'},...(Array.isArray(next.audit)?next.audit:[])].slice(0,1500);}
async function mutate(mutator,action='',entity='',id=null,description=''){const next=clone(state);await mutator(next);if(action)audit(next,action,entity,id,description);const result=await stateApi.save(next,stamp);state=result?.state||next;stamp=result?.updated_at||now();contracts=Array.isArray(state?.client_contracts)?state.client_contracts:[];clients=mergedClients(state,remoteClients);return state;}

function routerLabel(id){const router=routers.find((item)=>Number(item.id)===Number(id));return text(router?.name||router?.host)||'Sem MikroTik';}
function serviceStatus(row){return connectionMapStatus(row,liveByKey.get(row._serviceKey));}
function statusLabel(value){return value==='online'?'Online':value==='offline'?'Offline':value==='blocked'?'Bloqueado':'Sem leitura';}
function addressLabel(row){return [row?.address||row?.street,row?.address_number,row?.neighborhood,row?.city,row?.state].map(text).filter(Boolean).join(', ')||'Endereço não informado';}
function clientPopup(row,status){const phone=text(row?.phone||row?.whatsapp),digits=phone.replace(/\D/g,''),whatsapp=digits?`<a class="btn success" href="https://wa.me/${digits.startsWith('55')?digits:`55${digits}`}" target="_blank" rel="noopener noreferrer">WhatsApp</a>`:'';return `<strong>${esc(row._clientName||row.name||'Cliente')}</strong><p>${esc(row.contract_number||'Sem contrato')} · ${esc(row.pppoe_username||row.pppoe_user||'Sem PPPoE')}</p><p>${esc(addressLabel(row))}</p><p><b>${esc(statusLabel(status))}</b> · ${esc(routerLabel(row.router_id))}${liveByKey.get(row._serviceKey)?.uptime?` · uptime ${esc(liveByKey.get(row._serviceKey).uptime)}`:''}</p><div class="row-actions"><a class="btn secondary" href="/clientes">Abrir clientes</a>${whatsapp}</div>`;}
function ctoPopup(cto,ports,alertLevel=''){return `<strong>${esc(cto.name||'CTO')}</strong><p>${esc(addressLabel(cto))}</p><p><b>${ports.available} porta(s) livre(s)</b> · ${ports.used}/${ports.total} ocupadas</p><p>${esc(cto.pon?`PON ${cto.pon}`:'PON não informado')} · ${esc(routerLabel(cto.router_id))}</p><div class="row-actions"><button class="btn secondary" type="button" data-cto-edit="${esc(cto.id)}">Editar</button></div>${alertLevel?`<p><b>Atenção:</b> possível falha detectada nesta CTO.</p>`:''}`;}
function nodeTypeLabel(type){return text(type).toLowerCase()==='pop'?'POP':'Caixa de Emenda (CEO)';}
function nodePopup(node){const type=text(node.type).toLowerCase(),extra=type==='pop'?[node.reference,routerLabel(node.router_id)].map(text).filter(Boolean).join(' · '):`${Math.max(0,Math.trunc(Number(node.fiber_count)||0))||'—'} fibras / capacidade`;return `<strong>${esc(node.name||nodeTypeLabel(type))}</strong><p>${esc(nodeTypeLabel(type))} · ${esc(addressLabel(node))}</p><p>${esc(extra||'Sem referência adicional')}</p><div class="row-actions"><button class="btn secondary" type="button" data-node-edit="${esc(node.id)}">Editar</button></div>`;}

function buildMapMarkers(){
  const filter=$('#map-filter')?.value||'all',query=normalized($('#map-search')?.value),points=servicePoints(clients,contracts),alerts=networkOutageAlerts({state,clients,contracts,liveByKey,routers}),ctoAlertMap=new Map(alerts.filter((a)=>a.type==='cto').map((a)=>[text(a.cto?.id),a.level])),markers=[];
  for(const row of points){const lat=finite(row?.latitude),lng=finite(row?.longitude);if(lat===null||lng===null)continue;const status=serviceStatus(row),hay=normalized([row._clientName,row.contract_number,row.pppoe_username,row.pppoe_user,addressLabel(row)].join(' '));if(filter!=='all'&&status!==filter)continue;if(query&&!hay.includes(query))continue;markers.push({id:row._serviceKey,type:'client',status,lat,lng,label:row._clientName,popupHtml:clientPopup(row,status)});}
  for(const node of networkNodes(state)){const lat=finite(node.latitude),lng=finite(node.longitude);if(lat===null||lng===null)continue;const type=text(node.type).toLowerCase(),hay=normalized([node.name,node.type,node.reference,addressLabel(node),routerLabel(node.router_id)].join(' '));if(query&&!hay.includes(query))continue;markers.push({id:`node:${node.id}`,type,status:node.active===false?'warning':'',lat,lng,label:node.name,shortLabel:text(node.name)||nodeTypeLabel(type),subLabel:type==='pop'?'POP':'CEO',popupHtml:nodePopup(node)});}
  for(const cto of networkCtos(state)){const lat=finite(cto.latitude),lng=finite(cto.longitude);if(lat===null||lng===null)continue;const hay=normalized([cto.name,cto.address,cto.neighborhood,cto.city,cto.pon,routerLabel(cto.router_id)].join(' '));if(query&&!hay.includes(query)&&!points.some((row)=>text(row.cto_id)===text(cto.id)&&normalized([row._clientName,row.contract_number,row.pppoe_username].join(' ')).includes(query)))continue;const ports=ctoPortSummary(cto,clients,contracts),level=ctoAlertMap.get(text(cto.id))||'',status=level||(!ports.available?'critical':ports.available<=2?'warning':'');markers.push({id:`cto:${cto.id}`,type:'cto',status,lat,lng,label:cto.name,shortLabel:text(cto.name)||'CTO',subLabel:`${ports.available} livre${ports.available===1?'':'s'}`,popupHtml:ctoPopup(cto,ports,level)});}
  if(viabilityPoint)markers.push({id:'viability-point',type:'client',status:'unknown',lat:viabilityPoint.lat,lng:viabilityPoint.lng,label:'Endereço consultado',popupHtml:`<strong>Endereço consultado</strong><p>${esc(viabilityPoint.label||'Ponto de viabilidade')}</p>`});
  return markers;
}

function renderMapData({fit=false}={}){if(!map)return;const markers=buildMapMarkers(),segments=networkSegments(state);map.setData({markers,segments,draft:draftPoints});if((fit||!fitDone)&&markers.length){map.fit(markers);fitDone=true;}}
function renderStats(){const points=servicePoints(clients,contracts).filter((row)=>finite(row.latitude)!==null&&finite(row.longitude)!==null),online=points.filter((row)=>serviceStatus(row)==='online').length,offline=points.filter((row)=>serviceStatus(row)==='offline').length,ctos=networkCtos(state),pops=networkNodes(state,'pop'),ceos=networkNodes(state,'ceo'),free=ctos.reduce((sum,cto)=>sum+ctoPortSummary(cto,clients,contracts).available,0);$('#map-stats').innerHTML=`<article class="stat-card"><span>Clientes mapeados</span><strong>${points.length}</strong><small>com coordenada salva</small></article><article class="stat-card featured"><span>Online</span><strong>${online}</strong><small>sessões PPPoE ativas</small></article><article class="stat-card"><span>Offline</span><strong>${offline}</strong><small>acessos monitorados sem sessão</small></article><article class="stat-card"><span>POPs</span><strong>${pops.length}</strong><small>pontos de presença</small></article><article class="stat-card"><span>Caixas CEO</span><strong>${ceos.length}</strong><small>caixas de emenda</small></article><article class="stat-card"><span>CTOs</span><strong>${ctos.length}</strong><small>caixas cadastradas</small></article><article class="stat-card"><span>Portas livres</span><strong>${free}</strong><small>disponibilidade atual</small></article>`;}
function renderAlerts(){const root=$('#map-alerts'),alerts=networkOutageAlerts({state,clients,contracts,liveByKey,routers});if(!alerts.length){root.innerHTML='<div class="map-empty">Nenhuma concentração de quedas foi detectada com as leituras atuais. O sistema só alerta quando há vários acessos monitorados offline juntos.</div>';return;}root.innerHTML=alerts.slice(0,8).map((alert)=>`<article class="map-alert ${alert.level==='critical'?'critical':''}"><strong>${esc(alert.title)}</strong><span>${esc(alert.detail)}</span></article>`).join('');}
function renderNodes(){const root=$('#map-nodes'),nodes=networkNodes(state);if(!root)return;if(!nodes.length){root.innerHTML='<div class="map-empty">Nenhum POP ou Caixa de Emenda cadastrado ainda.</div>';return;}root.innerHTML=nodes.map((node)=>`<article class="map-list-item"><div><strong>${esc(node.name||nodeTypeLabel(node.type))}</strong><span>${esc(nodeTypeLabel(node.type))}</span><small>${esc(addressLabel(node))}</small></div><div class="row-actions"><button class="btn secondary" type="button" data-node-edit="${esc(node.id)}">Editar</button><button class="btn danger" type="button" data-node-delete="${esc(node.id)}">Excluir</button></div></article>`).join('');}
function renderCtos(){const root=$('#map-ctos'),ctos=networkCtos(state);if(!ctos.length){root.innerHTML='<div class="map-empty">Nenhuma CTO cadastrada. Cadastre a primeira para liberar controle de portas e viabilidade.</div>';return;}root.innerHTML=ctos.map((cto)=>{const ports=ctoPortSummary(cto,clients,contracts);return `<article class="map-list-item"><div><strong>${esc(cto.name||'CTO')}</strong><span>${ports.used}/${ports.total} ocupadas · ${ports.available} livres</span><small>${esc(cto.pon?`PON ${cto.pon} · `:'')}${esc(routerLabel(cto.router_id))}</small></div><div class="row-actions"><button class="btn secondary" type="button" data-cto-edit="${esc(cto.id)}">Editar</button><button class="btn danger" type="button" data-cto-delete="${esc(cto.id)}">Excluir</button></div></article>`;}).join('');}
function renderSegments(){const root=$('#map-segments'),segments=networkSegments(state);if(!segments.length){root.innerHTML='<div class="map-empty">Nenhum trecho desenhado. Use “Desenhar fibra” e clique no mapa seguindo o caminho real da rede.</div>';return;}root.innerHTML=segments.map((segment)=>`<article class="map-list-item"><div><strong>${esc(segment.name||'Trecho')}</strong><span>${Number(segment.fibers)||0} fibra(s) · ${segment.points.length} ponto(s)</span><small>${esc(segment.status||'Ativo')}</small></div><button class="btn danger" type="button" data-segment-delete="${esc(segment.id)}">Excluir</button></article>`).join('');}
function renderAll(options={}){renderStats();renderAlerts();renderNodes();renderCtos();renderSegments();renderMapData(options);}

async function refreshBaseData(){
  const [stateResult,clientRows,routerRows]=await Promise.all([stateApi.load(),dataApi.clients(),dataApi.routers()]);
  state=stateResult?.state&&typeof stateResult.state==='object'?stateResult.state:{};stamp=stateResult?.updated_at||stamp;remoteClients=Array.isArray(clientRows)?clientRows:[];routers=Array.isArray(routerRows)?routerRows:[];clients=mergedClients(state,remoteClients);contracts=Array.isArray(state?.client_contracts)?state.client_contracts:[];
}

async function refreshLive(force=false){
  if(liveBusy)return;liveBusy=true;const button=$('#map-refresh');if(button){button.disabled=true;button.textContent=force?'Atualizando…':'Consultando…';}
  try{
    await refreshBaseData();
    const points=servicePoints(clients,contracts).filter((row)=>normalized(row.connection_type)==='pppoe'&&Number(row.router_id)>0&&text(row.pppoe_username||row.pppoe_user)),byRouter=new Map();for(const row of points){const list=byRouter.get(Number(row.router_id))||[];list.push(row);byRouter.set(Number(row.router_id),list);}
    const next=new Map();
    await Promise.all([...byRouter.entries()].map(async([routerId,rows])=>{const router=routers.find((item)=>Number(item.id)===routerId);if(!router||router.active===false)return;try{const secret=await dataApi.routerSecret(routerId);if(!secret?.password)throw new Error('Senha do MikroTik não cadastrada.');const snapshot=await mikrotikApi.run('router.sync',{...router,password:secret.password});if(snapshot?.warning)throw new Error(snapshot.warning);const active=new Map((Array.isArray(snapshot?.pppActive)?snapshot.pppActive:[]).map((item)=>[normalized(item?.name),item]).filter(([name])=>Boolean(name))),checkedAt=snapshot?.lastSync||now();for(const row of rows){const session=active.get(normalized(row.pppoe_username||row.pppoe_user));next.set(row._serviceKey,{state:session?'online':'offline',checkedAt,ip:text(session?.address),uptime:text(session?.uptime),callerId:text(session?.['caller-id'])});}}catch(error){console.warn(`Mapa: não foi possível consultar MikroTik ${routerId}.`,error);}}));
    liveByKey=next;if(!infrastructureDragging)renderAll();
  }finally{liveBusy=false;if(button){button.disabled=false;button.textContent='Atualizar agora';}}
}

function cepDigits(value){return String(value??'').replace(/\D/g,'').slice(0,8);}
function formatCep(value){const digits=cepDigits(value);return digits.length>5?`${digits.slice(0,5)}-${digits.slice(5)}`:digits;}
function addressStatus(form,message=''){const status=form?.querySelector?.('[data-address-status]');if(status)status.textContent=message;}
async function fillAddressByCep(form){const cep=cepDigits(form?.elements?.zip_code?.value);if(!form||cep.length!==8)return false;if(form.dataset.cepLoading===cep)return false;if(form.dataset.cepLoaded===cep)return true;form.dataset.cepLoading=cep;addressStatus(form,'Consultando CEP…');try{const response=await fetch(`https://viacep.com.br/ws/${cep}/json/`,{headers:{Accept:'application/json'},cache:'no-store'});if(!response.ok)throw new Error(`Não foi possível consultar o CEP (HTTP ${response.status}).`);const result=await response.json();if(result?.erro)throw new Error('CEP não encontrado. Confira o número informado.');form.elements.zip_code.value=formatCep(cep);if(form.elements.address)form.elements.address.value=text(result.logradouro);if(form.elements.neighborhood)form.elements.neighborhood.value=text(result.bairro);if(form.elements.city)form.elements.city.value=text(result.localidade);if(form.elements.state)form.elements.state.value=text(result.uf).toUpperCase();form.dataset.cepLoaded=cep;addressStatus(form,'CEP encontrado. Endereço preenchido automaticamente.');return true;}catch(error){addressStatus(form,error.message);toast(error.message,'error');return false;}finally{delete form.dataset.cepLoading;}}
async function locateInfrastructure(form){const button=form.querySelector('[data-map-locate]');if(button)button.disabled=true;addressStatus(form,'Localizando endereço no mapa…');try{const found=await geocodeAddress({address:form.elements.address.value,number:form.elements.address_number.value,neighborhood:form.elements.neighborhood.value,city:form.elements.city.value,state:form.elements.state.value,zip_code:form.elements.zip_code.value});form.elements.latitude.value=found.lat.toFixed(7);form.elements.longitude.value=found.lng.toFixed(7);addressStatus(form,found.displayName);}catch(error){addressStatus(form,error.message);toast(error.message,'error');}finally{if(button)button.disabled=false;}}
function resolveFormPosition(fd,existing={}){const latitudeRaw=text(fd.get('latitude')),longitudeRaw=text(fd.get('longitude')),view=map?.getView?.()||{},latitude=latitudeRaw?Number(latitudeRaw):(finite(existing?.latitude)??finite(view.lat)),longitude=longitudeRaw?Number(longitudeRaw):(finite(existing?.longitude)??finite(view.lng));return {latitude,longitude};}

function ctoForm(cto={}){const routerOptions=['<option value="">Sem MikroTik vinculado</option>',...routers.map((row)=>`<option value="${esc(row.id)}"${String(row.id)===String(cto.router_id)?' selected':''}>${esc(row.name||row.host)}</option>`)].join(''),positionFields=cto.id?`<label>Latitude<input name="latitude" type="number" step="any" value="${esc(cto.latitude??'')}"></label><label>Longitude<input name="longitude" type="number" step="any" value="${esc(cto.longitude??'')}"></label>`:`<input type="hidden" name="latitude" value=""><input type="hidden" name="longitude" value="">`;return `<form class="map-form" id="cto-form"><input type="hidden" name="id" value="${esc(cto.id||'')}"><label>Nome / código da CTO<input name="name" value="${esc(cto.name||'')}" placeholder="Ex.: CTO-023" required></label><label>Total de portas<input name="total_ports" type="number" min="1" max="512" value="${esc(cto.total_ports||8)}" required></label><label>CEP<input name="zip_code" inputmode="numeric" maxlength="9" autocomplete="postal-code" value="${esc(cto.zip_code||'')}" placeholder="00000-000"></label><label>Número<input name="address_number" value="${esc(cto.address_number||'')}"></label><label class="span-2">Endereço<input name="address" value="${esc(cto.address||'')}"></label><label>Bairro<input name="neighborhood" value="${esc(cto.neighborhood||'')}"></label><label>Cidade<input name="city" value="${esc(cto.city||'')}"></label><label>UF<input name="state" value="${esc(cto.state||'')}" maxlength="2"></label>${positionFields}<div class="span-2 row-actions"><button class="btn secondary" data-map-locate type="button">Localizar no mapa</button><span class="hint" data-address-status>Digite o CEP para preencher o endereço automaticamente.</span></div><label>PON<input name="pon" value="${esc(cto.pon||'')}" placeholder="Ex.: 0/2/5"></label><label>OLT / referência<input name="olt" value="${esc(cto.olt||'')}"></label><label>MikroTik<select name="router_id">${routerOptions}</select></label><label>Portas reservadas<input name="reserved_ports" value="${esc(parsePortList(cto.reserved_ports).join(', '))}" placeholder="Ex.: 2, 5"></label><label>Portas com defeito<input name="defect_ports" value="${esc(parsePortList(cto.defect_ports).join(', '))}" placeholder="Ex.: 8"></label><label class="check"><input name="active" type="checkbox" ${cto.active===false?'':'checked'}> CTO ativa</label><label class="span-2">Observação<textarea name="notes">${esc(cto.notes||'')}</textarea></label><div class="map-form-actions"><button class="btn secondary" type="button" data-map-close>Cancelar</button><button class="btn primary" type="submit">Salvar CTO</button></div></form>`;}
function openCto(id=''){const cto=networkCtos(state).find((item)=>text(item.id)===text(id))||{};modal(cto.id?`Editar ${cto.name||'CTO'}`:'Nova CTO',ctoForm(cto));}
async function saveCto(form){
  const fd=new FormData(form),id=text(fd.get('id'))||crypto.randomUUID(),existing=networkCtos(state).find((item)=>text(item.id)===id),position=resolveFormPosition(fd,existing),total=Math.max(1,Math.min(512,Math.trunc(Number(fd.get('total_ports'))||8))),reserved=parsePortList(fd.get('reserved_ports')),defect=parsePortList(fd.get('defect_ports')),overlap=reserved.filter((port)=>defect.includes(port));if(overlap.length)throw new Error(`A porta ${overlap[0]} não pode estar reservada e com defeito ao mesmo tempo.`);if([...reserved,...defect].some((port)=>port>total))throw new Error('Há porta reservada ou com defeito acima do total de portas da CTO.');
  const assigned=assignmentMap(clients,contracts),usedPorts=[];for(const [key] of assigned){const [ctoId,portRaw]=key.split(':');if(ctoId===id)usedPorts.push(Number(portRaw));}if(usedPorts.some((port)=>port>total))throw new Error(`Existem clientes usando porta acima de ${total}. Mova esses clientes antes de reduzir a CTO.`);if(usedPorts.some((port)=>reserved.includes(port)||defect.includes(port)))throw new Error('Uma porta ocupada por cliente não pode ser marcada como reservada ou defeituosa.');
  const row={...(existing||{}),id,name:text(fd.get('name')),total_ports:total,address:text(fd.get('address')),address_number:text(fd.get('address_number')),neighborhood:text(fd.get('neighborhood')),city:text(fd.get('city')),state:text(fd.get('state')).toUpperCase(),zip_code:formatCep(fd.get('zip_code')),latitude:position.latitude,longitude:position.longitude,pon:text(fd.get('pon')),olt:text(fd.get('olt')),router_id:Number(fd.get('router_id'))||null,reserved_ports:reserved,defect_ports:defect,active:fd.get('active')==='on',notes:text(fd.get('notes')),updated_at:now(),created_at:existing?.created_at||now()};if(!row.name||!Number.isFinite(row.latitude)||!Number.isFinite(row.longitude))throw new Error('Informe o nome da CTO.');
  await mutate((next)=>{const mapState=networkMapState(next),list=[...mapState.ctos],index=list.findIndex((item)=>text(item.id)===id);if(index>=0)list[index]=row;else list.push(row);next.network_map={...(next.network_map||{}),ctos:list};},existing?'cto_editada':'cto_criada','cto',id,row.name);closeModal();renderAll({fit:!fitDone});toast(existing?'CTO atualizada.':'CTO cadastrada. Arraste no mapa para ajustar a posição.');
}
async function deleteCto(id){const cto=networkCtos(state).find((item)=>text(item.id)===text(id));if(!cto)return;const linked=servicePoints(clients,contracts).filter((row)=>text(row.cto_id)===text(id));if(linked.length)return toast(`Esta CTO possui ${linked.length} cliente(s)/contrato(s) vinculados. Mova os vínculos antes de excluir.`,'error');if(!confirm(`Excluir ${cto.name||'esta CTO'}?`))return;await mutate((next)=>{const mapState=networkMapState(next);next.network_map={...(next.network_map||{}),ctos:mapState.ctos.filter((item)=>text(item.id)!==text(id))};},'cto_excluida','cto',id,cto.name);renderAll();toast('CTO excluída.');}

function nodeForm(type,node={}){const isPop=type==='pop',routerOptions=['<option value="">Sem MikroTik vinculado</option>',...routers.map((row)=>`<option value="${esc(row.id)}"${String(row.id)===String(node.router_id)?' selected':''}>${esc(row.name||row.host)}</option>`)].join(''),positionFields=node.id?`<label>Latitude<input name="latitude" type="number" step="any" value="${esc(node.latitude??'')}"></label><label>Longitude<input name="longitude" type="number" step="any" value="${esc(node.longitude??'')}"></label>`:`<input type="hidden" name="latitude" value=""><input type="hidden" name="longitude" value="">`;return `<form class="map-form" id="node-form" data-node-type="${esc(type)}"><input type="hidden" name="id" value="${esc(node.id||'')}"><label>Nome / código<input name="name" value="${esc(node.name||'')}" placeholder="${isPop?'Ex.: POP-CENTRO':'Ex.: CEO-014'}" required></label>${isPop?`<label>MikroTik<select name="router_id">${routerOptions}</select></label>`:`<label>Capacidade / fibras<input name="fiber_count" type="number" min="0" max="3456" value="${esc(node.fiber_count||'')}"></label>`}<label>CEP<input name="zip_code" inputmode="numeric" maxlength="9" autocomplete="postal-code" value="${esc(node.zip_code||'')}" placeholder="00000-000"></label><label>Número<input name="address_number" value="${esc(node.address_number||'')}"></label><label class="span-2">Endereço<input name="address" value="${esc(node.address||'')}"></label><label>Bairro<input name="neighborhood" value="${esc(node.neighborhood||'')}"></label><label>Cidade<input name="city" value="${esc(node.city||'')}"></label><label>UF<input name="state" value="${esc(node.state||'')}" maxlength="2"></label>${positionFields}<div class="span-2 row-actions"><button class="btn secondary" data-map-locate type="button">Localizar no mapa</button><span class="hint" data-address-status>Digite o CEP para preencher o endereço automaticamente.</span></div><label class="span-2">${isPop?'OLT / referência do POP':'Cabo / referência da emenda'}<input name="reference" value="${esc(node.reference||'')}"></label><label class="check"><input name="active" type="checkbox" ${node.active===false?'':'checked'}> ${isPop?'POP ativo':'CEO ativa'}</label><label class="span-2">Observação<textarea name="notes">${esc(node.notes||'')}</textarea></label><div class="map-form-actions"><button class="btn secondary" type="button" data-map-close>Cancelar</button><button class="btn primary" type="submit">Salvar ${isPop?'POP':'CEO'}</button></div></form>`;}
function openNode(type,id=''){const cleanType=type==='pop'?'pop':'ceo',node=networkNodes(state).find((item)=>text(item.id)===text(id)&&text(item.type).toLowerCase()===cleanType)||{};modal(node.id?`Editar ${node.name||nodeTypeLabel(cleanType)}`:`Novo ${nodeTypeLabel(cleanType)}`,nodeForm(cleanType,node));}
async function saveNode(form){const fd=new FormData(form),type=form.dataset.nodeType==='pop'?'pop':'ceo',id=text(fd.get('id'))||crypto.randomUUID(),existing=networkNodes(state).find((item)=>text(item.id)===id),position=resolveFormPosition(fd,existing),row={...(existing||{}),id,type,name:text(fd.get('name')),address:text(fd.get('address')),address_number:text(fd.get('address_number')),neighborhood:text(fd.get('neighborhood')),city:text(fd.get('city')),state:text(fd.get('state')).toUpperCase(),zip_code:formatCep(fd.get('zip_code')),latitude:position.latitude,longitude:position.longitude,router_id:type==='pop'?(Number(fd.get('router_id'))||null):null,fiber_count:type==='ceo'?Math.max(0,Math.trunc(Number(fd.get('fiber_count'))||0)):0,reference:text(fd.get('reference')),active:fd.get('active')==='on',notes:text(fd.get('notes')),updated_at:now(),created_at:existing?.created_at||now()};if(!row.name||!Number.isFinite(row.latitude)||!Number.isFinite(row.longitude))throw new Error(`Informe o nome do ${type==='pop'?'POP':'CEO'}.`);await mutate((next)=>{const mapState=networkMapState(next),list=[...mapState.nodes],index=list.findIndex((item)=>text(item.id)===id);if(index>=0)list[index]=row;else list.push(row);next.network_map={...(next.network_map||{}),nodes:list};},existing?`${type}_editado`:`${type}_criado`,type,id,row.name);closeModal();renderAll({fit:!fitDone});toast(existing?`${type==='pop'?'POP':'CEO'} atualizado.`:`${type==='pop'?'POP':'CEO'} cadastrado. Arraste no mapa para ajustar a posição.`);}
async function deleteNode(id){const node=networkNodes(state).find((item)=>text(item.id)===text(id));if(!node)return;if(!confirm(`Excluir ${node.name||nodeTypeLabel(node.type)}?`))return;await mutate((next)=>{const mapState=networkMapState(next);next.network_map={...(next.network_map||{}),nodes:mapState.nodes.filter((item)=>text(item.id)!==text(id))};},`${node.type}_excluido`,node.type,id,node.name);renderAll();toast(`${nodeTypeLabel(node.type)} excluído.`);}

function viabilityForm(){return `<form class="map-form" id="viability-form"><label>CEP<input name="zip_code" inputmode="numeric" maxlength="9" autocomplete="postal-code" placeholder="00000-000"></label><label>Número<input name="address_number" required></label><label class="span-2">Endereço<input name="address" required placeholder="Rua / avenida"></label><label>Bairro<input name="neighborhood"></label><label>Cidade<input name="city" required></label><label>UF<input name="state" maxlength="2" required></label><div class="span-2"><span class="hint" data-address-status>Digite o CEP para preencher o endereço automaticamente.</span></div><div class="map-form-actions"><button class="btn secondary" type="button" data-map-close>Cancelar</button><button class="btn primary" type="submit">Analisar endereço</button></div><div class="span-2" id="viability-result"></div></form>`;}
function openViability(){modal('Consultar viabilidade',viabilityForm());}
async function analyzeViability(form){const resultRoot=$('#viability-result'),submit=form.querySelector('button[type="submit"]');submit.disabled=true;submit.textContent='Analisando…';try{const address={address:form.elements.address.value,number:form.elements.address_number.value,neighborhood:form.elements.neighborhood.value,city:form.elements.city.value,state:form.elements.state.value,zip_code:form.elements.zip_code.value},found=await geocodeAddress(address),analysis=findViability({lat:found.lat,lng:found.lng,state,clients,contracts});viabilityPoint={lat:found.lat,lng:found.lng,label:found.displayName};renderMapData();map.setView(found.lat,found.lng,17);const recommended=analysis.recommendation,nearest=analysis.nearest,rows=analysis.items.slice(0,6).map((item)=>`<article class="viability-item ${recommended&&text(recommended.cto.id)===text(item.cto.id)?'recommended':''}"><div><strong>${esc(item.cto.name||'CTO')}</strong><span>${item.distance} m · ${item.ports.available} porta(s) livre(s) · ${item.ports.used}/${item.ports.total} ocupadas</span><small>${item.networkDistance===null?'Traçado de fibra ainda não mapeado':`Rede mapeada a aproximadamente ${item.networkDistance} m do endereço`} · ${esc(item.cto.pon?`PON ${item.cto.pon}`:'PON não informado')}</small></div>${recommended&&text(recommended.cto.id)===text(item.cto.id)?'<span class="viability-badge">RECOMENDADA</span>':item.ports.available===0?'<span class="viability-badge">LOTADA</span>':''}</article>`).join('');let message='';if(recommended){message=nearest&&text(nearest.cto.id)!==text(recommended.cto.id)&&nearest.ports.available===0?`A CTO mais próxima (${nearest.cto.name}) está lotada. O sistema encontrou ${recommended.cto.name} a ${recommended.distance} m com porta disponível.`:`Melhor opção: ${recommended.cto.name}, a ${recommended.distance} m, com ${recommended.ports.available} porta(s) disponível(is).`;}else if(analysis.nearestFree){message=`Não há CTO com porta livre dentro do raio configurado de ${analysis.maxDistanceM} m. A primeira com disponibilidade é ${analysis.nearestFree.cto.name}, a ${analysis.nearestFree.distance} m.`;}else message='Nenhuma CTO com porta disponível foi encontrada.';resultRoot.innerHTML=`<p class="hint"><strong>${esc(message)}</strong></p><div class="viability-list">${rows||'<div class="map-empty">Cadastre CTOs com localização para calcular a viabilidade.</div>'}</div>`;}catch(error){resultRoot.innerHTML=`<p class="hint danger-text">${esc(error.message)}</p>`;}finally{submit.disabled=false;submit.textContent='Analisar endereço';}}

function setDrawing(active){drawing=active;$('#map-draw-bar')?.classList.toggle('active',active);if(!active){draftPoints=[];renderMapData();}updateDrawNote();}
function updateDrawNote(){const note=$('#map-draw-note');if(note)note.textContent=drawing?`${draftPoints.length} ponto(s) marcado(s). Clique no mapa seguindo o caminho real da fibra.`:'Clique no mapa para marcar o caminho da fibra.';}
async function saveSegment(){if(draftPoints.length<2)return toast('Marque pelo menos dois pontos no mapa.','error');const name=text($('#map-segment-name')?.value)||'Trecho de fibra',fibers=Math.max(1,Math.min(576,Math.trunc(Number($('#map-segment-fibers')?.value)||12))),row={id:crypto.randomUUID(),name,fibers,points:draftPoints.map((p)=>({lat:Number(p.lat.toFixed(7)),lng:Number(p.lng.toFixed(7))})),status:'Ativo',created_at:now(),updated_at:now()};await mutate((next)=>{const mapState=networkMapState(next);next.network_map={...(next.network_map||{}),segments:[...mapState.segments,row]};},'trecho_rede_criado','network_segment',row.id,row.name);setDrawing(false);renderAll();toast('Trecho de fibra salvo no mapa.');}
async function deleteSegment(id){const segment=networkSegments(state).find((item)=>text(item.id)===text(id));if(!segment||!confirm(`Excluir o trecho ${segment.name||''}?`))return;await mutate((next)=>{const mapState=networkMapState(next);next.network_map={...(next.network_map||{}),segments:mapState.segments.filter((item)=>text(item.id)!==text(id))};},'trecho_rede_excluido','network_segment',id,segment.name);renderAll();toast('Trecho removido.');}

async function loadBase(){const auth=await authApi.status();if(!auth?.authenticated||!auth?.user){location.replace('/central');return false;}user=auth.user;if(!canUseNetwork()){location.replace('/central');return false;}await refreshBaseData();return true;}
async function focusCurrentLocation(){if(!navigator.geolocation||!map)return false;return new Promise((resolve)=>{navigator.geolocation.getCurrentPosition((position)=>{const lat=finite(position?.coords?.latitude),lng=finite(position?.coords?.longitude);if(lat===null||lng===null){resolve(false);return;}fitDone=true;map.setView(lat,lng,16);resolve(true);},(error)=>{if(Number(error?.code)===1)toast('Permita o acesso à localização no navegador para o mapa abrir onde você está.','error');resolve(false);},{enableHighAccuracy:true,timeout:8000,maximumAge:60000});});}
function mapPointFromPointer(clientX,clientY){const container=$('#network-map'),view=map?.getView();if(!container||!view)return null;const rect=container.getBoundingClientRect(),x=Math.max(0,Math.min(rect.width,clientX-rect.left)),y=Math.max(0,Math.min(rect.height,clientY-rect.top)),worldSize=256*2**Number(view.zoom),centerX=(Number(view.lng)+180)/360*worldSize,s=Math.sin(Number(view.lat)*Math.PI/180),centerY=(.5-Math.log((1+s)/(1-s))/(4*Math.PI))*worldSize,worldX=centerX+x-rect.width/2,worldY=centerY+y-rect.height/2,lng=worldX/worldSize*360-180,n=Math.PI-2*Math.PI*worldY/worldSize,lat=Math.atan(Math.sinh(n))*180/Math.PI;return {lat,lng,x,y};}
async function saveInfrastructurePosition(markerId,type,point){const cleanType=type==='cto'?'cto':type==='pop'?'pop':'ceo',id=cleanType==='cto'?text(markerId).replace(/^cto:/,''):text(markerId).replace(/^node:/,''),current=cleanType==='cto'?networkCtos(state).find((item)=>text(item.id)===id):networkNodes(state).find((item)=>text(item.id)===id);if(!current||!Number.isFinite(point?.lat)||!Number.isFinite(point?.lng)){renderMapData();return;}const label=cleanType==='cto'?'CTO':cleanType==='pop'?'POP':'CEO';if(!confirm(`Salvar ${label} ${current.name||''} nesta nova posição?`)){renderMapData();return;}const latitude=Number(point.lat.toFixed(7)),longitude=Number(point.lng.toFixed(7));await mutate((next)=>{const mapState=networkMapState(next);if(cleanType==='cto'){next.network_map={...(next.network_map||{}),ctos:mapState.ctos.map((item)=>text(item.id)===id?{...item,latitude,longitude,updated_at:now()}:item)};}else{next.network_map={...(next.network_map||{}),nodes:mapState.nodes.map((item)=>text(item.id)===id?{...item,latitude,longitude,updated_at:now()}:item)};}},`${cleanType}_reposicionado`,cleanType,id,current.name);renderAll();toast(`${label} reposicionado no mapa.`);}
function bindInfrastructureDrag(){const container=$('#network-map');if(!container)return;let drag=null,suppressClick=false;container.addEventListener('pointerdown',(event)=>{const marker=event.target.closest('.map-marker.cto,.map-marker.pop,.map-marker.ceo');if(!marker)return;const type=marker.classList.contains('cto')?'cto':marker.classList.contains('pop')?'pop':'ceo';drag={node:marker,id:marker.dataset.mapMarker,type,pointerId:event.pointerId,startX:event.clientX,startY:event.clientY,moved:false};infrastructureDragging=true;marker.setPointerCapture?.(event.pointerId);event.preventDefault();});container.addEventListener('pointermove',(event)=>{if(!drag||event.pointerId!==drag.pointerId)return;if(Math.abs(event.clientX-drag.startX)+Math.abs(event.clientY-drag.startY)>3)drag.moved=true;if(!drag.moved)return;const point=mapPointFromPointer(event.clientX,event.clientY);if(!point)return;drag.node.style.left=`${point.x}px`;drag.node.style.top=`${point.y}px`;event.preventDefault();});container.addEventListener('pointerup',(event)=>{if(!drag||event.pointerId!==drag.pointerId)return;const active=drag;drag=null;infrastructureDragging=false;active.node.releasePointerCapture?.(event.pointerId);if(!active.moved){renderMapData();return;}const point=mapPointFromPointer(event.clientX,event.clientY);suppressClick=true;setTimeout(()=>{suppressClick=false;},0);saveInfrastructurePosition(active.id,active.type,point).catch((error)=>{renderMapData();toast(error?.message||String(error),'error');});});container.addEventListener('pointercancel',(event)=>{if(!drag||event.pointerId!==drag.pointerId)return;drag=null;infrastructureDragging=false;renderMapData();});container.addEventListener('click',(event)=>{if(!suppressClick||!event.target.closest('.map-marker.cto,.map-marker.pop,.map-marker.ceo'))return;suppressClick=false;event.preventDefault();event.stopImmediatePropagation();},true);}

function bind(){
  $('#map-refresh')?.addEventListener('click',()=>refreshLive(true));$('#map-new-pop')?.addEventListener('click',()=>openNode('pop'));$('#map-new-ceo')?.addEventListener('click',()=>openNode('ceo'));$('#map-new-cto')?.addEventListener('click',()=>openCto());$('#map-viability')?.addEventListener('click',openViability);$('#map-draw')?.addEventListener('click',()=>setDrawing(true));$('#map-draw-cancel')?.addEventListener('click',()=>setDrawing(false));$('#map-draw-undo')?.addEventListener('click',()=>{draftPoints.pop();renderMapData();updateDrawNote();});$('#map-draw-save')?.addEventListener('click',()=>saveSegment().catch((e)=>toast(e.message,'error')));$('#map-zoom-in')?.addEventListener('click',()=>map?.zoomIn());$('#map-zoom-out')?.addEventListener('click',()=>map?.zoomOut());$('#map-fit')?.addEventListener('click',()=>map?.fit(buildMapMarkers()));$('#map-search')?.addEventListener('input',()=>renderMapData());$('#map-filter')?.addEventListener('change',()=>renderMapData());
  document.addEventListener('input',(event)=>{const input=event.target.closest('input[name="zip_code"]');if(!input)return;input.value=formatCep(input.value);if(cepDigits(input.value).length===8){const form=input.form;if(form)void fillAddressByCep(form);}});
  document.addEventListener('click',(event)=>{if(event.target.matches('[data-map-close]')||event.target.matches('[data-map-close-backdrop]'))return closeModal();const editNode=event.target.closest('[data-node-edit]');if(editNode){const node=networkNodes(state).find((item)=>text(item.id)===text(editNode.dataset.nodeEdit));if(node)return openNode(text(node.type).toLowerCase(),node.id);}const delNode=event.target.closest('[data-node-delete]');if(delNode)return deleteNode(delNode.dataset.nodeDelete).catch((e)=>toast(e.message,'error'));const edit=event.target.closest('[data-cto-edit]');if(edit)return openCto(edit.dataset.ctoEdit);const del=event.target.closest('[data-cto-delete]');if(del)return deleteCto(del.dataset.ctoDelete).catch((e)=>toast(e.message,'error'));const segment=event.target.closest('[data-segment-delete]');if(segment)return deleteSegment(segment.dataset.segmentDelete).catch((e)=>toast(e.message,'error'));const locate=event.target.closest('[data-map-locate]');if(locate){const form=locate.closest('.map-form');if(form)return void locateInfrastructure(form);}});
  document.addEventListener('submit',(event)=>{const form=event.target;if(form?.id==='cto-form'){event.preventDefault();saveCto(form).catch((e)=>toast(e.message,'error'));}if(form?.id==='node-form'){event.preventDefault();saveNode(form).catch((e)=>toast(e.message,'error'));}if(form?.id==='viability-form'){event.preventDefault();analyzeViability(form);}});
}

async function start(){try{if(!await loadBase())return;map=createNetworkMap($('#network-map'),{onMapClick:(point)=>{if(!drawing)return;draftPoints.push(point);renderMapData();updateDrawNote();}});bind();bindInfrastructureDrag();renderAll({fit:true});await focusCurrentLocation();await refreshLive(false);liveTimer=setInterval(()=>{void refreshLive(false);},10000);}catch(error){console.error(error);toast(error?.message||String(error),'error');}}

window.addEventListener('beforeunload',()=>{if(liveTimer)clearInterval(liveTimer);map?.destroy();});
void start();
