import baseWorker from './customer-service-worker.js';
import {neon} from '@neondatabase/serverless';
import {handleBankProxy} from './worker-bank-native.js';

const STATE_KEY='web_state_v1017';
const BANK_SETTINGS_KEY='bank_credentials_v1';
const PORTAL_PATH='/api/customer-portal';
const ORIGINS=new Set(['https://cliente.fibramais.workers.dev','https://client.fibramais.workers.dev']);
const utf8=new TextEncoder();
const text=value=>String(value??'').trim();
const digits=value=>text(value).replace(/\D/g,'');
const number=value=>{const n=Number(value);return Number.isFinite(n)?n:null};

function json(data,status=200,headers={}){return new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store, max-age=0',...headers}})}
function cors(request){const origin=text(request.headers.get('origin')),headers={'Vary':'Origin','Access-Control-Allow-Methods':'POST,OPTIONS','Access-Control-Allow-Headers':'Content-Type','Access-Control-Max-Age':'86400'};if(ORIGINS.has(origin))headers['Access-Control-Allow-Origin']=origin;return headers}
function parseState(value){if(value&&typeof value==='object'&&!Array.isArray(value))return value;if(typeof value==='string')try{const parsed=JSON.parse(value);return parsed&&typeof parsed==='object'&&!Array.isArray(parsed)?parsed:{}}catch{}return {}}
async function loadState(sql){const rows=await sql`SELECT value FROM pp_settings WHERE key=${STATE_KEY} LIMIT 1`;return parseState(rows?.[0]?.value)}
async function saveState(sql,state){const raw=JSON.stringify(state||{}),at=new Date().toISOString();await sql`INSERT INTO pp_settings (key,value,updated_at) VALUES (${STATE_KEY},${raw}::jsonb,${at}) ON CONFLICT (key) DO UPDATE SET value=EXCLUDED.value,updated_at=EXCLUDED.updated_at`;return at}
function b64urlBytes(value){let raw=text(value).replace(/-/g,'+').replace(/_/g,'/');while(raw.length%4)raw+='=';const bin=atob(raw),out=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)out[i]=bin.charCodeAt(i);return out}
async function portalKey(env){const secret=text(env.PORTAL_SESSION_SECRET)||text(env.DATABASE_URL);if(!secret)throw Object.assign(new Error('Sua sessão segura não está disponível no momento.'),{statusCode:503});return crypto.subtle.importKey('raw',utf8.encode(secret),{name:'HMAC',hash:'SHA-256'},false,['verify'])}
async function verifySession(token,env){const parts=text(token).split('.');if(parts.length!==2)throw Object.assign(new Error('Sua sessão expirou. Entre novamente.'),{statusCode:401});try{const key=await portalKey(env),ok=await crypto.subtle.verify('HMAC',key,b64urlBytes(parts[1]),utf8.encode(parts[0]));if(!ok)throw new Error('assinatura');const payload=JSON.parse(new TextDecoder().decode(b64urlBytes(parts[0]))),clientId=Number(payload?.clientId)||0,exp=Number(payload?.exp)||0;if(!clientId||exp<=Date.now())throw new Error('expirada');return {clientId,token:text(token)}}catch{throw Object.assign(new Error('Sua sessão expirou. Entre novamente.'),{statusCode:401})}}
async function portalClient(sql,id){const rows=await sql`SELECT id,name,document,contract_number,plan,plan_id,due_day,status,email,phone,address,city,state,zip_code FROM pp_clients WHERE id=${Number(id)} LIMIT 1`;return rows?.[0]||null}

function bankBytes(value){const bin=atob(text(value)),out=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)out[i]=bin.charCodeAt(i);return out}
async function bankKey(env){const secret=text(env.BANK_SECRET_KEY)||text(env.PORTAL_SESSION_SECRET)||text(env.DATABASE_URL);if(!secret)throw Object.assign(new Error('O serviço de cobrança não está disponível no momento.'),{statusCode:503});const raw=await crypto.subtle.digest('SHA-256',utf8.encode(`provedor-plus-bank-v1|${secret}`));return crypto.subtle.importKey('raw',raw,{name:'AES-GCM'},false,['decrypt'])}
async function decryptBankSettings(env,record){if(!record?.iv||!record?.data)return {};try{const key=await bankKey(env),plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:bankBytes(record.iv)},key,bankBytes(record.data)),parsed=JSON.parse(new TextDecoder().decode(plain));return parsed&&typeof parsed==='object'?parsed:{}}catch{throw Object.assign(new Error('Não foi possível preparar a instituição de pagamento para este acordo.'),{statusCode:503})}}
async function readBankSettings(env){const sql=neon(env.DATABASE_URL),rows=await sql`SELECT value FROM pp_settings WHERE key=${BANK_SETTINGS_KEY} LIMIT 1`;return rows?.[0]?.value?decryptBankSettings(env,rows[0].value):{}}
function bankSecrets(vault){return {efi:{environment:text(vault?.efi?.environment)||'sandbox',clientId:text(vault?.efi?.clientId),clientSecret:text(vault?.efi?.clientSecret),certificatePassword:String(vault?.efi?.certificatePassword||''),certificateBase64:String(vault?.efi?.certificateBase64||''),pixKey:text(vault?.efi?.pixKey),pixAutoReceiverAgency:text(vault?.efi?.pixAutoReceiverAgency),pixAutoReceiverAccount:text(vault?.efi?.pixAutoReceiverAccount),webhookUrl:text(vault?.efi?.webhookUrl)},mercadoPago:{environment:text(vault?.mercadoPago?.environment)||'sandbox',publicKey:text(vault?.mercadoPago?.publicKey),accessToken:text(vault?.mercadoPago?.accessToken)}}}
function stateClient(state,client){return (Array.isArray(state?.clients)?state.clients:[]).find(row=>Number(row?.id)===Number(client.id))||{}}
function bankClient(client,state){const local=stateClient(state,client),plan=state?.plans?.find?.(row=>Number(row?.id)===Number(local.plan_id||client.plan_id));return {...local,...client,plan_name:text(plan?.name||client.plan||local.plan)||'Serviço de internet',plan_speed:text(plan?.speed)}}
function bankInvoice(invoice,client,state){const local=stateClient(state,client),plan=state?.plans?.find?.(row=>Number(row?.id)===Number(local.plan_id||client.plan_id));return {...invoice,client_name:text(client.name),client_phone:text(client.phone),client_whatsapp:text(local.whatsapp||client.phone),client_document:text(client.document),client_email:text(client.email),client_neighborhood:text(local.neighborhood),client_cep:text(local.cep||client.zip_code),client_street:text(local.street||client.address),client_address_number:text(local.address_number),client_complement:text(local.complement),client_city:text(client.city),client_state:text(client.state),client_contract_number:text(client.contract_number),client_status:text(client.status),client_plan:text(plan?.name||client.plan)||'Serviço de internet'}}
async function bankContext(env,state,client,selected){const vault=await readBankSettings(env),ready=[];if(vault?.efi?.enabled&&text(vault.efi.clientId)&&text(vault.efi.clientSecret))ready.push('efi');if(vault?.mercadoPago?.enabled&&text(vault.mercadoPago.accessToken))ready.push('mercadoPago');if(!ready.length)throw Object.assign(new Error('A negociação está temporariamente indisponível para emissão. Entre em contato com o suporte.'),{statusCode:409});const local=stateClient(state,client),original=[...new Set((selected||[]).map(row=>text(row?.bank_provider)).filter(provider=>ready.includes(provider)))],candidates=[text(local.billing_bank_provider),text(state?.banks?.defaultProvider),original.length===1?original[0]:''];let provider=candidates.find(value=>ready.includes(value))||'';if(!provider&&ready.length===1)provider=ready[0];if(!provider)throw Object.assign(new Error('A negociação está temporariamente indisponível. Entre em contato com o suporte.'),{statusCode:409});return {provider,secrets:bankSecrets(vault)}}
async function bankProxy(env,payload){const response=await handleBankProxy(new Request('https://painel.fibramais.workers.dev/api/bank-proxy',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}),env);let body={};try{body=await response.json()}catch{}if(!response.ok||!body.ok)throw Object.assign(new Error(body?.error||'Não foi possível concluir a emissão das cobranças do acordo.'),{statusCode:response.status>=400&&response.status<500?409:502});return body.data||{}}

function invoiceCents(row){for(const key of ['amount_cents','total_cents','value_cents','price_cents']){const n=number(row?.[key]);if(n!==null)return Math.max(0,Math.round(n))}for(const key of ['amount','total','value','price']){const n=number(row?.[key]);if(n!==null)return Math.max(0,Math.round(n*100))}return 0}
function invoiceReference(row){const explicit=text(row?.reference||row?.competency||row?.competence||row?.month||row?.period);if(explicit)return explicit;const match=text(row?.due_date||row?.dueDate).slice(0,10).match(/^(\d{4})-(\d{2})-/);return match?`${match[2]}/${match[1]}`:''}
function brl(cents){return new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format((Number(cents)||0)/100)}
function formatDate(value){const match=text(value).slice(0,10).match(/^(\d{4})-(\d{2})-(\d{2})$/);return match?`${match[3]}/${match[2]}/${match[1]}`:text(value)}
function bounded(value,fallback,min,max){const n=Number(value);return Number.isFinite(n)?Math.max(min,Math.min(max,n)):fallback}
function boolValue(value,fallback){if(value===undefined||value===null||value==='')return fallback;if(typeof value==='boolean')return value;const v=text(value).toLowerCase();if(['true','1','sim','yes','on'].includes(v))return true;if(['false','0','nao','não','no','off'].includes(v))return false;return fallback}
function rulesFor(state){const settings=state?.settings||{},version=Number(settings.negotiation_policy_version)||0,enabled=boolValue(settings.negotiation_auto_enabled,true);if(version<2)return {policyVersion:2,enabled,minOverdueDays:5,cashDiscountPercent:5,installmentInterestPercent:1.5,maxInstallments:3,entryPercent:30,firstDueDays:0};return {policyVersion:2,enabled,minOverdueDays:Math.floor(bounded(settings.negotiation_min_overdue_days,5,0,365)),cashDiscountPercent:bounded(settings.negotiation_cash_discount_percent,5,0,100),installmentInterestPercent:bounded(settings.negotiation_installment_interest_percent,1.5,0,20),maxInstallments:Math.floor(bounded(settings.negotiation_max_installments,3,2,3)),entryPercent:bounded(settings.negotiation_entry_percent,30,0,90),firstDueDays:Math.floor(bounded(settings.negotiation_first_due_days,0,0,30))}}
function todayKey(){const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date()),map={};for(const part of parts)map[part.type]=part.value;return `${map.year}-${map.month}-${map.day}`}
function dateFromKey(value){const m=text(value).slice(0,10).match(/^(\d{4})-(\d{2})-(\d{2})$/);return m?new Date(Date.UTC(Number(m[1]),Number(m[2])-1,Number(m[3]),12)):null}
function dateKey(date){return `${date.getUTCFullYear()}-${String(date.getUTCMonth()+1).padStart(2,'0')}-${String(date.getUTCDate()).padStart(2,'0')}`}
function addDays(key,days){const date=dateFromKey(key)||new Date();date.setUTCDate(date.getUTCDate()+Number(days||0));return dateKey(date)}
function addMonths(key,months){const date=dateFromKey(key)||new Date(),day=date.getUTCDate();date.setUTCDate(1);date.setUTCMonth(date.getUTCMonth()+Number(months||0));const last=new Date(Date.UTC(date.getUTCFullYear(),date.getUTCMonth()+1,0,12)).getUTCDate();date.setUTCDate(Math.min(day,last));return dateKey(date)}
function overdueDays(key){const due=dateFromKey(key),today=dateFromKey(todayKey());if(!due||!today||due>=today)return 0;return Math.floor((today-due)/86400000)}
function eligibleInvoice(row,clientId,rules){if(Number(row?.client_id)!==Number(clientId))return false;const status=text(row?.status).toLowerCase();if(['pago','paid','baixado','cancelado','canceled','renegociado','renegotiated','substituido','substituida'].some(value=>status.includes(value)))return false;if(text(row?.negotiation_id))return false;const due=text(row?.due_date||row?.dueDate).slice(0,10),days=overdueDays(due);return Boolean(due)&&days>=rules.minOverdueDays&&days>0&&invoiceCents(row)>0}
function distribute(total,parts){const qty=Math.max(1,Number(parts)||1),base=Math.floor(total/qty),extra=total-base*qty;return Array.from({length:qty},(_,i)=>base+(i<extra?1:0))}
function installmentProposal(baseCents,qty,entryPercent,interestPercent,firstDueDate){const total=Math.max(qty,Math.round(baseCents)),count=Math.max(2,Math.round(qty));let entry=Math.round(total*entryPercent/100);entry=Math.max(1,Math.min(total-(count-1),entry));const financed=Math.max(0,total-entry),periods=count-1,rate=Math.max(0,Number(interestPercent)||0)/100;let financedWithInterest=financed;if(financed>0&&rate>0){const factor=Math.pow(1+rate,periods),payment=financed*(rate*factor)/(factor-1);financedWithInterest=Math.max(financed,Math.round(payment*periods))}const interest=Math.max(0,financedWithInterest-financed),amounts=distribute(financedWithInterest,periods),schedule=[{number:1,dueDate:firstDueDate,amountCents:entry},...amounts.map((amount,index)=>({number:index+2,dueDate:addMonths(firstDueDate,index+1),amountCents:amount}))];return {entryCents:entry,financedCents:financed,interestCents:interest,totalCents:entry+financedWithInterest,schedule}}
function buildOptions(state,client,invoiceIds){const rules=rulesFor(state),all=Array.isArray(state?.invoices)?state.invoices:[],eligible=all.filter(row=>eligibleInvoice(row,client.id,rules)),explicit=Array.isArray(invoiceIds),wanted=new Set((invoiceIds||[]).map(String)),selected=explicit?eligible.filter(row=>wanted.has(String(row.id))):eligible,originalCents=selected.reduce((sum,row)=>sum+invoiceCents(row),0),firstDueDate=addDays(todayKey(),rules.firstDueDays),options=[];if(originalCents>0){const discountCents=Math.min(originalCents-1,Math.max(0,Math.round(originalCents*rules.cashDiscountPercent/100))),cashTotal=Math.max(1,originalCents-discountCents);options.push({id:'cash',proposalType:'cash',label:'À vista',installments:1,discountPercent:rules.cashDiscountPercent,discountCents,interestPercent:0,interestCents:0,financedCents:0,totalCents:cashTotal,entryCents:cashTotal,firstDueDate,schedule:[{number:1,dueDate:firstDueDate,amountCents:cashTotal}]});for(let qty=2;qty<=rules.maxInstallments;qty++){const calc=installmentProposal(originalCents,qty,rules.entryPercent,rules.installmentInterestPercent,firstDueDate);options.push({id:`p${qty}`,proposalType:'installment',label:`Parcelado em ${qty}x`,installments:qty,discountPercent:0,discountCents:0,interestPercent:rules.installmentInterestPercent,interestCents:calc.interestCents,financedCents:calc.financedCents,totalCents:calc.totalCents,entryCents:calc.entryCents,firstDueDate,schedule:calc.schedule})}}return {enabled:rules.enabled,rules,eligibleInvoices:eligible.map(row=>({id:row.id,reference:invoiceReference(row),dueDate:formatDate(row.due_date||row.dueDate),dueDateRaw:text(row.due_date||row.dueDate),daysOverdue:overdueDays(text(row.due_date||row.dueDate).slice(0,10)),amountCents:invoiceCents(row),total:brl(invoiceCents(row)),status:text(row.status)||'Pendente'})),selectedInvoiceIds:selected.map(row=>row.id),originalCents,originalTotal:brl(originalCents),options}}
function nextInvoiceId(state){const invoices=Array.isArray(state?.invoices)?state.invoices:[],max=Math.max(Number(state?.seq?.invoices)||0,...invoices.map(row=>Number(row?.id)||0)),id=max+1;state.seq={...(state.seq||{}),invoices:id};return id}

async function ensureProtocols(sql){await sql`CREATE TABLE IF NOT EXISTS pp_protocols (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,protocol TEXT UNIQUE,client_id BIGINT NULL REFERENCES pp_clients(id) ON DELETE SET NULL,category TEXT NOT NULL,subject TEXT NOT NULL,source TEXT NOT NULL DEFAULT 'provedor-plus',status TEXT NOT NULL DEFAULT 'Aberto',created_by_user_id BIGINT NULL REFERENCES pp_users(id) ON DELETE SET NULL,created_by_name TEXT NULL,details JSONB NOT NULL DEFAULT '{}'::jsonb,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),closed_at TIMESTAMPTZ NULL)`;await sql`CREATE INDEX IF NOT EXISTS pp_protocols_client_created_idx ON pp_protocols (client_id,created_at DESC)`}
function protocolCode(id,createdAt){const d=new Date(createdAt||Date.now()),stamp=`${d.getUTCFullYear()}${String(d.getUTCMonth()+1).padStart(2,'0')}${String(d.getUTCDate()).padStart(2,'0')}`;return `PP-${stamp}-${String(Number(id)||0).padStart(6,'0')}`}
async function createProtocol(sql,clientId,details){await ensureProtocols(sql);const raw=JSON.stringify(details||{}),rows=await sql`INSERT INTO pp_protocols (client_id,category,subject,source,status,created_by_name,details) VALUES (${Number(clientId)},'Negociação','Acordo de débitos','area-cliente','Em processamento','Área do Cliente',${raw}::jsonb) RETURNING *`,row=rows?.[0];if(!row?.id)throw new Error('Não foi possível gerar o protocolo do acordo.');const protocol=protocolCode(row.id,row.created_at);await sql`UPDATE pp_protocols SET protocol=${protocol} WHERE id=${Number(row.id)}`;return {id:Number(row.id),protocol,createdAt:text(row.created_at)}}
async function finishProtocol(sql,protocol,status,details){const raw=JSON.stringify(details||{}),rows=await sql`UPDATE pp_protocols SET status=${status},details=${raw}::jsonb,closed_at=now() WHERE protocol=${protocol} RETURNING id,protocol,status,created_at,closed_at`;const row=rows?.[0];return row?{id:Number(row.id),protocol:text(row.protocol),status:text(row.status),createdAt:text(row.created_at),closedAt:text(row.closed_at)}:null}
async function ensureSingleProcessing(sql,clientId,protocolId){const rows=await sql`SELECT id FROM pp_protocols WHERE client_id=${Number(clientId)} AND category='Negociação' AND subject='Acordo de débitos' AND status='Em processamento' AND created_at>=now()-interval '15 minutes' ORDER BY id ASC LIMIT 1`;return Number(rows?.[0]?.id)===Number(protocolId)}

async function refreshPortal(baseRequest,env,ctx,session){const origin=text(baseRequest.headers.get('origin'))||'https://cliente.fibramais.workers.dev',request=new Request('https://painel.fibramais.workers.dev/api/customer-portal',{method:'POST',headers:{'Content-Type':'application/json','Origin':origin},body:JSON.stringify({action:'refresh',data:{session}})}),response=await baseWorker.fetch(request,env,ctx);let body={};try{body=await response.json()}catch{}return response.ok&&body?.ok?body.data||{}:null}
async function optionsFor(env,data){const session=await verifySession(data?.session,env),sql=neon(env.DATABASE_URL),client=await portalClient(sql,session.clientId);if(!client)throw Object.assign(new Error('Cliente não encontrado.'),{statusCode:404});const state=await loadState(sql),preview=buildOptions(state,client,Array.isArray(data?.invoiceIds)?data.invoiceIds:undefined);let bankReady=false,bankMessage='';if(preview.enabled&&preview.selectedInvoiceIds.length){const ids=new Set(preview.selectedInvoiceIds.map(String)),selected=(state.invoices||[]).filter(row=>ids.has(String(row.id)));try{await bankContext(env,state,client,selected);bankReady=true}catch(error){bankMessage=error instanceof Error?error.message:String(error)}}return {...preview,bankReady,bankMessage}}
async function negotiate(request,env,ctx,data){const session=await verifySession(data?.session,env),sql=neon(env.DATABASE_URL),client=await portalClient(sql,session.clientId);if(!client)throw Object.assign(new Error('Cliente não encontrado.'),{statusCode:404});const state=await loadState(sql),preview=buildOptions(state,client,Array.isArray(data?.invoiceIds)?data.invoiceIds:[]),rules=preview.rules;if(!rules.enabled)throw Object.assign(new Error('A negociação automática não está disponível no momento.'),{statusCode:409});if(!preview.selectedInvoiceIds.length)throw Object.assign(new Error('Selecione pelo menos uma fatura vencida disponível para negociação.'),{statusCode:400});const option=preview.options.find(item=>item.id===text(data?.optionId));if(!option)throw Object.assign(new Error('Escolha uma proposta válida.'),{statusCode:400});const selectedKeys=new Set(preview.selectedInvoiceIds.map(String)),selected=(state.invoices||[]).filter(row=>selectedKeys.has(String(row.id)));if(selected.length!==preview.selectedInvoiceIds.length)throw Object.assign(new Error('Uma das faturas foi atualizada. Recalcule o acordo antes de confirmar.'),{statusCode:409});const bank=await bankContext(env,state,client,selected),protocol=await createProtocol(sql,client.id,{requestedAt:new Date().toISOString(),originalInvoiceIds:preview.selectedInvoiceIds,proposalType:option.proposalType,originalAmountCents:preview.originalCents,discountCents:option.discountCents,interestPercent:option.interestPercent,interestCents:option.interestCents,entryCents:option.entryCents,installmentTotal:option.installments,negotiatedAmountCents:option.totalCents});if(!await ensureSingleProcessing(sql,client.id,protocol.id)){await finishProtocol(sql,protocol.protocol,'Negado',{reason:'parallel_request'});throw Object.assign(new Error('Já existe uma confirmação de acordo em andamento. Aguarde alguns instantes.'),{statusCode:409})}
  const nextState=JSON.parse(JSON.stringify(state||{}));nextState.invoices=Array.isArray(nextState.invoices)?nextState.invoices:[];nextState.negotiations=Array.isArray(nextState.negotiations)?nextState.negotiations:[];const agreementId=`NEG-${Number(client.id)}-${Date.now().toString(36).toUpperCase()}`,createdAt=new Date().toISOString(),newInvoices=[];
  for(const part of option.schedule){const id=nextInvoiceId(nextState);newInvoices.push({id,client_id:Number(client.id),due_date:part.dueDate,amount_cents:Number(part.amountCents)||0,status:'Pendente',document_type:'Boleto',billing_type:'Renegociação',description:`Acordo ${agreementId} · Parcela ${part.number}/${option.installments}`,installment_group:agreementId,installment_number:part.number,installment_total:option.installments,payment_method:'',paid_by:'',paid_at:null,created_at:createdAt,bank_provider:bank.provider,negotiation_id:agreementId,negotiation_origin:'customer_portal_auto',negotiation_protocol:protocol.protocol,negotiation_proposal_type:option.proposalType,negotiation_interest_percent:option.interestPercent,negotiation_interest_cents:option.interestCents,negotiated_invoice_ids:[...preview.selectedInvoiceIds],cashback_eligible:false,cashback_enabled:false,cashback_reason:'renegociacao',reference:part.dueDate.slice(0,7),competency:part.dueDate.slice(0,7)})}
  const issued=[];let staged=false,oldCanceled=false;
  try{
    for(const invoice of newInvoices){const remote=await bankProxy(env,{action:'issue',provider:bank.provider,invoice:bankInvoice(invoice,client,nextState),client:bankClient(client,nextState),efi:bank.secrets.efi,mercadoPago:bank.secrets.mercadoPago,pixAutoRecord:null});Object.assign(invoice,remote||{});issued.push(invoice)}
    const replacementIds=newInvoices.map(row=>row.id),agreement={id:agreementId,client_id:Number(client.id),protocol:protocol.protocol,original_invoice_ids:[...preview.selectedInvoiceIds],original_amount_cents:preview.originalCents,discount_cents:option.discountCents,interest_percent:option.interestPercent,interest_cents:option.interestCents,proposal_type:option.proposalType,negotiated_amount_cents:option.totalCents,entry_cents:option.entryCents,installment_total:option.installments,bank_provider:bank.provider,origin:'customer_portal_auto',status:'Em processamento',created_at:createdAt,new_invoice_ids:replacementIds};
    nextState.invoices.push(...newInvoices);nextState.negotiations.push(agreement);nextState.negotiations=nextState.negotiations.slice(-1000);await saveState(sql,nextState);staged=true;
    for(const old of selected){if(!text(old?.bank_provider))continue;await bankProxy(env,{action:'cancel',invoice:bankInvoice(old,client,state),efi:bank.secrets.efi,mercadoPago:bank.secrets.mercadoPago})}
    oldCanceled=true;
    for(const old of nextState.invoices){if(!selectedKeys.has(String(old.id)))continue;Object.assign(old,{status:'Renegociado',negotiation_id:agreementId,negotiated_at:createdAt,negotiated_by:'Área do Cliente',replaced_by_invoice_ids:replacementIds,cashback_eligible:false,cashback_enabled:false})}
    agreement.status='Ativo';agreement.confirmed_at=new Date().toISOString();nextState.audit=Array.isArray(nextState.audit)?nextState.audit:[];nextState.audit.unshift({id:Date.now(),action:'customer_portal_negotiation',entity:'negotiation',entity_id:agreementId,client_id:Number(client.id),protocol:protocol.protocol,created_at:createdAt});nextState.audit=nextState.audit.slice(0,1000);await saveState(sql,nextState);
    const completed=await finishProtocol(sql,protocol.protocol,'Concluído',{agreementId,proposalType:option.proposalType,originalInvoiceIds:[...preview.selectedInvoiceIds],originalAmountCents:preview.originalCents,discountCents:option.discountCents,interestPercent:option.interestPercent,interestCents:option.interestCents,financedCents:option.financedCents,entryCents:option.entryCents,negotiatedAmountCents:option.totalCents,installmentTotal:option.installments,newInvoiceIds:replacementIds,confirmedAt:agreement.confirmed_at});const portal=await refreshPortal(request,env,ctx,session.token);return {agreement:{id:agreementId,protocol:protocol.protocol,status:'Ativo',createdAt,proposalType:option.proposalType,originalAmountCents:preview.originalCents,discountCents:option.discountCents,interestPercent:option.interestPercent,interestCents:option.interestCents,financedCents:option.financedCents,negotiatedAmountCents:option.totalCents,entryCents:option.entryCents,installmentTotal:option.installments,newInvoiceIds:replacementIds},protocol:completed||{protocol:protocol.protocol,status:'Concluído'},portal};
  }catch(error){let rollbackFailed=false;if(!oldCanceled){for(const invoice of issued.reverse())try{await bankProxy(env,{action:'cancel',invoice:bankInvoice(invoice,client,nextState),efi:bank.secrets.efi,mercadoPago:bank.secrets.mercadoPago})}catch{rollbackFailed=true}if(staged)try{await saveState(sql,state)}catch{rollbackFailed=true}}const message=error instanceof Error?error.message:String(error);try{await finishProtocol(sql,protocol.protocol,'Falhou',{agreementId,error:message,issuedInvoiceIds:issued.map(row=>row.id),oldChargesCanceled:oldCanceled,rollbackFailed,failedAt:new Date().toISOString()})}catch{};throw Object.assign(new Error(oldCanceled||rollbackFailed?'O acordo não pôde ser finalizado automaticamente. Nenhuma nova tentativa deve ser feita agora; entre em contato com o suporte informando o protocolo '+protocol.protocol+'.':message),{statusCode:Number(error?.statusCode)||502})}
}

async function handleNegotiation(request,env,ctx){const headers=cors(request),origin=text(request.headers.get('origin'));if(request.method==='OPTIONS')return new Response(null,{status:204,headers});if(request.method!=='POST')return json({ok:false,error:'Método não permitido.'},405,headers);if(origin&&!ORIGINS.has(origin))return json({ok:false,error:'Origem não autorizada.'},403,headers);if(!env.DATABASE_URL)return json({ok:false,error:'A negociação está temporariamente indisponível.'},503,headers);try{let body={};try{body=await request.json()}catch{}const action=text(body?.action),data=body?.data||{};if(action==='negotiation-options')return json({ok:true,data:await optionsFor(env,data)},200,headers);if(action==='negotiate')return json({ok:true,data:await negotiate(request,env,ctx,data)},200,headers);return baseWorker.fetch(request,env,ctx)}catch(error){return json({ok:false,error:error instanceof Error?error.message:String(error)},Number(error?.statusCode)||500,headers)}}

export default {
  fetch(request,env,ctx){const url=new URL(request.url);if(url.pathname===PORTAL_PATH&&request.method==='OPTIONS')return handleNegotiation(request,env,ctx);if(url.pathname===PORTAL_PATH&&request.method==='POST')return request.clone().json().then(body=>['negotiation-options','negotiate'].includes(text(body?.action))?handleNegotiation(request,env,ctx):baseWorker.fetch(request,env,ctx)).catch(()=>baseWorker.fetch(request,env,ctx));return baseWorker.fetch(request,env,ctx)},
  scheduled(controller,env,ctx){return baseWorker.scheduled(controller,env,ctx)}
};
