(()=>{
'use strict';
const API='/api/push-admin';
const $=(s,r=document)=>r.querySelector(s);
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

async function api(action,data={}){
  const response=await fetch(API,{method:'POST',credentials:'same-origin',cache:'no-store',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,data})});
  let body={};try{body=await response.json()}catch{}
  if(!response.ok||!body.ok)throw new Error(body.error||`Falha ao acessar notificações (HTTP ${response.status}).`);
  return body.data||{};
}
function ensureStyle(){if($('#pp-push-manager-style'))return;const style=document.createElement('style');style.id='pp-push-manager-style';style.textContent=`
.pp-push-open{width:calc(100% - 24px);margin:8px 12px;padding:10px 12px;border:1px solid rgba(255,255,255,.16);border-radius:10px;background:rgba(255,255,255,.08);color:inherit;font:700 12px/1.2 Segoe UI,Arial,sans-serif;cursor:pointer;display:flex;align-items:center;gap:9px}.pp-push-open svg{width:17px;height:17px;fill:none;stroke:currentColor;stroke-width:1.8}.pp-push-open:hover{background:rgba(255,255,255,.13)}
.pp-push-layer{position:fixed;inset:0;z-index:2147482600;display:grid;place-items:center;padding:18px;background:rgba(14,24,30,.48);backdrop-filter:blur(4px)}.pp-push-modal{width:min(94vw,720px);max-height:min(90vh,760px);overflow:auto;border-radius:18px;background:#fff;color:#233533;box-shadow:0 30px 80px rgba(0,0,0,.24);font-family:Segoe UI,Arial,sans-serif}.pp-push-head{display:flex;justify-content:space-between;align-items:center;gap:16px;padding:20px 22px;border-bottom:1px solid #e8efed}.pp-push-head h2{margin:0;font-size:18px}.pp-push-head p{margin:4px 0 0;color:#758783;font-size:11px}.pp-push-close{width:34px;height:34px;border:0;border-radius:9px;background:#f1f5f4;color:#60706d;font-size:18px;cursor:pointer}.pp-push-body{padding:20px 22px;display:grid;gap:16px}.pp-push-stats{display:grid;grid-template-columns:1fr 1fr;gap:10px}.pp-push-stat{padding:13px 14px;border:1px solid #e4ecea;border-radius:12px;background:#f8fbfa}.pp-push-stat span,.pp-push-stat strong{display:block}.pp-push-stat span{font-size:9px;color:#7d8d89;text-transform:uppercase;letter-spacing:.5px}.pp-push-stat strong{margin-top:4px;font-size:21px;color:#156f62}.pp-push-form{display:grid;gap:11px}.pp-push-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.pp-push-field{display:grid;gap:5px}.pp-push-field span{font-size:10px;font-weight:800;color:#596d68}.pp-push-field input,.pp-push-field select,.pp-push-field textarea{width:100%;box-sizing:border-box;border:1px solid #d9e4e1;border-radius:9px;background:#fff;color:#263a36;font:12px Segoe UI,Arial,sans-serif;padding:10px 11px;outline:none}.pp-push-field textarea{min-height:92px;resize:vertical}.pp-push-field input:focus,.pp-push-field select:focus,.pp-push-field textarea:focus{border-color:#179c86;box-shadow:0 0 0 3px rgba(23,156,134,.1)}.pp-push-send{height:42px;border:0;border-radius:10px;background:#0b8f7c;color:#fff;font-weight:850;cursor:pointer}.pp-push-send:disabled{opacity:.55;cursor:wait}.pp-push-result{min-height:17px;padding:9px 11px;border-radius:9px;background:#f5f8f7;color:#62746f;font-size:11px}.pp-push-result.ok{background:#e9f7f2;color:#14745f}.pp-push-result.error{background:#fff0ed;color:#a24c3c}.pp-push-history h3{margin:0 0 8px;font-size:12px}.pp-push-history-list{display:grid;gap:7px}.pp-push-history-item{display:grid;grid-template-columns:1fr auto;gap:8px;padding:10px 11px;border:1px solid #e8efed;border-radius:10px}.pp-push-history-item b,.pp-push-history-item span,.pp-push-history-item small{display:block}.pp-push-history-item b{font-size:11px}.pp-push-history-item span{margin-top:2px;color:#6f817d;font-size:10px}.pp-push-history-item small{color:#91a09d;font-size:9px}.pp-push-history-count{align-self:center;font-size:10px;font-weight:800;color:#14745f}.pp-push-empty{padding:12px;text-align:center;color:#8b9a97;font-size:10px}
@media(max-width:620px){.pp-push-layer{padding:8px}.pp-push-modal{width:100%;max-height:96vh;border-radius:14px}.pp-push-head,.pp-push-body{padding:16px}.pp-push-grid,.pp-push-stats{grid-template-columns:1fr}}
`;document.head.appendChild(style)}
function fmtDate(value){const d=new Date(value);return Number.isNaN(d.getTime())?'':d.toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'})}
function renderHistory(items=[]){const host=$('[data-pp-push-history]');if(!host)return;host.innerHTML=items.length?items.map(item=>`<div class="pp-push-history-item"><div><b>${esc(item.title)}</b><span>${esc(item.body)}</span><small>${esc(item.target_mode==='all'?'Todos os clientes':'Cliente específico')} · ${esc(fmtDate(item.created_at))} · ${esc(item.created_by_name||'Administrador')}</small></div><div class="pp-push-history-count">${Number(item.sent_count)||0} enviada${Number(item.sent_count)===1?'':'s'}${Number(item.failed_count)?` · ${Number(item.failed_count)} falha${Number(item.failed_count)===1?'':'s'}`:''}</div></div>`).join(''):'<div class="pp-push-empty">Nenhuma notificação enviada ainda.</div>'}
async function refresh(){const data=await api('stats');const devices=$('[data-pp-push-devices]'),clients=$('[data-pp-push-clients]');if(devices)devices.textContent=String(data.devices||0);if(clients)clients.textContent=String(data.clients||0);renderHistory(data.history||[])}
function openModal(){
  if($('.pp-push-layer'))return;ensureStyle();const layer=document.createElement('div');layer.className='pp-push-layer';layer.innerHTML=`<section class="pp-push-modal" role="dialog" aria-modal="true" aria-label="Central de Notificações"><header class="pp-push-head"><div><h2>Central de Notificações</h2><p>Envie avisos para a barra de notificação dos dispositivos autorizados.</p></div><button class="pp-push-close" type="button" aria-label="Fechar">×</button></header><div class="pp-push-body"><div class="pp-push-stats"><article class="pp-push-stat"><span>Dispositivos autorizados</span><strong data-pp-push-devices>—</strong></article><article class="pp-push-stat"><span>Clientes com notificações</span><strong data-pp-push-clients>—</strong></article></div><form class="pp-push-form"><div class="pp-push-grid"><label class="pp-push-field"><span>Destinatário</span><select name="mode"><option value="client">Um cliente</option><option value="all">Todos os clientes autorizados</option></select></label><label class="pp-push-field" data-pp-push-identifier><span>CPF/CNPJ ou contrato</span><input name="identifier" autocomplete="off" placeholder="Informe o cliente"></label></div><label class="pp-push-field"><span>Título</span><input name="title" maxlength="90" required placeholder="Ex.: Sua fatura está disponível"></label><label class="pp-push-field"><span>Mensagem</span><textarea name="body" maxlength="500" required placeholder="Digite a mensagem que aparecerá no celular do cliente."></textarea></label><label class="pp-push-field"><span>Ao tocar, abrir</span><select name="url"><option value="/">Início da Área do Cliente</option><option value="/#faturas">Faturas</option><option value="/#conexao">Minha conexão</option><option value="/#perfil">Meus dados</option></select></label><button class="pp-push-send" type="submit">Enviar notificação</button><div class="pp-push-result" data-pp-push-result>Pronto para enviar.</div></form><section class="pp-push-history"><h3>Últimos envios</h3><div class="pp-push-history-list" data-pp-push-history><div class="pp-push-empty">Carregando...</div></div></section></div></section>`;document.body.appendChild(layer);
  const close=()=>layer.remove();$('.pp-push-close',layer).onclick=close;layer.addEventListener('click',e=>{if(e.target===layer)close()});const form=$('.pp-push-form',layer),mode=form.elements.mode,identifier=$('[data-pp-push-identifier]',layer),result=$('[data-pp-push-result]',layer),send=$('.pp-push-send',layer);mode.addEventListener('change',()=>{identifier.style.display=mode.value==='all'?'none':'grid'});
  form.addEventListener('submit',async event=>{event.preventDefault();result.className='pp-push-result';result.textContent='Enviando...';send.disabled=true;try{const data=await api('send',{mode:mode.value,identifier:form.elements.identifier.value,title:form.elements.title.value,body:form.elements.body.value,url:form.elements.url.value});result.className='pp-push-result ok';result.textContent=`Enviada para ${data.sent||0} dispositivo${Number(data.sent)===1?'':'s'}${data.failed?` · ${data.failed} falha${Number(data.failed)===1?'':'s'}`:''}.`;form.elements.body.value='';await refresh()}catch(error){result.className='pp-push-result error';result.textContent=error.message||String(error)}finally{send.disabled=false}});
  refresh().catch(error=>{result.className='pp-push-result error';result.textContent=error.message||String(error)});
}
function mount(){ensureStyle();const sidebar=$('.sidebar');if(!sidebar||sidebar.querySelector('[data-pp-push-open]'))return;const button=document.createElement('button');button.type='button';button.className='pp-push-open';button.dataset.ppPushOpen='1';button.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4"/></svg><span>Notificações</span>';button.addEventListener('click',event=>{event.preventDefault();event.stopPropagation();openModal()});const logout=sidebar.querySelector('[data-logout],.logout');logout?logout.insertAdjacentElement('beforebegin',button):sidebar.appendChild(button)}
mount();const observer=new MutationObserver(()=>mount());observer.observe(document.documentElement,{childList:true,subtree:true});
window.ProvedorPlusPush={open:openModal,refresh};
})();