import coreWorker from './negotiation-worker.js';
import {neon} from '@neondatabase/serverless';
import {buildPushHTTPRequest} from '@pushforge/builder';

const CLIENT_PUSH_PATH='/api/customer-push';
const ADMIN_PUSH_PATH='/api/push-admin';
const VAPID_KEY='push_vapid_v1';
const STATE_KEY='web_state_v1017';
const CLIENT_ORIGINS=new Set(['https://cliente.fibramais.workers.dev','https://client.fibramais.workers.dev']);
const CLIENT_APP_ORIGIN='https://cliente.fibramais.workers.dev';
const DAY=86400000;
const text=value=>String(value??'').trim();
const digits=value=>text(value).replace(/\D/g,'');
const enc=new TextEncoder();
let schemaReady=false;

function json(data,status=200,headers={}){return new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store, max-age=0',...headers}})}
function clientCors(request){const origin=text(request.headers.get('origin')),headers={'Vary':'Origin','Access-Control-Allow-Methods':'POST,OPTIONS','Access-Control-Allow-Headers':'Content-Type','Access-Control-Max-Age':'86400'};if(CLIENT_ORIGINS.has(origin))headers['Access-Control-Allow-Origin']=origin;return headers}
function base64Url(bytes){const view=bytes instanceof Uint8Array?bytes:new Uint8Array(bytes);let raw='';for(let i=0;i<view.length;i+=0x8000)raw+=String.fromCharCode(...view.subarray(i,Math.min(i+0x8000,view.length)));return btoa(raw).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function base64UrlBytes(value){const raw=text(value).replace(/-/g,'+').replace(/_/g,'/'),padded=raw+'='.repeat((4-raw.length%4)%4),bin=atob(padded),out=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)out[i]=bin.charCodeAt(i);return out}
function parseState(value){if(value&&typeof value==='object'&&!Array.isArray(value))return value;if(typeof value==='string')try{const parsed=JSON.parse(value);return parsed&&typeof parsed==='object'&&!Array.isArray(parsed)?parsed:{}}catch{}return {}}
async function loadState(sql){const rows=await sql`SELECT value FROM pp_settings WHERE key=${STATE_KEY} LIMIT 1`;return parseState(rows?.[0]?.value)}
function normalizeStatus(value){return text(value).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'')}
function paidStatus(value){const status=normalizeStatus(value);return ['pago','paga','paid','baixado','recebido','recebida','quitado','quitada'].some(item=>status.includes(item))}
function inactiveStatus(value){const status=normalizeStatus(value);return ['cancelado','canceled','renegociado','renegotiated','substituido','substituida'].some(item=>status.includes(item))}
function invoiceOpen(invoice){return !paidStatus(invoice?.status)&&!inactiveStatus(invoice?.status)}
function invoiceCents(invoice){for(const key of ['amount_cents','total_cents','value_cents','price_cents']){const n=Number(invoice?.[key]);if(Number.isFinite(n))return Math.max(0,Math.round(n))}for(const key of ['amount','total','value','price']){const n=Number(invoice?.[key]);if(Number.isFinite(n))return Math.max(0,Math.round(n*100))}return 0}
function brl(cents){return new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format((Number(cents)||0)/100)}
function brazilDateKey(date=new Date()){const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(date),map={};for(const part of parts)map[part.type]=part.value;return `${map.year}-${map.month}-${map.day}`}
function dateFromKey(value){const match=text(value).slice(0,10).match(/^(\d{4})-(\d{2})-(\d{2})$/);return match?new Date(Date.UTC(Number(match[1]),Number(match[2])-1,Number(match[3]),12)):null}
function addDaysKey(value,days){const date=dateFromKey(value);if(!date)return'';date.setUTCDate(date.getUTCDate()+Number(days||0));return `${date.getUTCFullYear()}-${String(date.getUTCMonth()+1).padStart(2,'0')}-${String(date.getUTCDate()).padStart(2,'0')}`}
function brDate(value){const match=text(value).slice(0,10).match(/^(\d{4})-(\d{2})-(\d{2})$/);return match?`${match[3]}/${match[2]}/${match[1]}`:text(value)}
function recentTimestamp(value,hours=36){const time=new Date(value).getTime();return Number.isFinite(time)&&Date.now()-time>=0&&Date.now()-time<=hours*60*60*1000}

async function ensurePushTables(sql){
  if(schemaReady)return;
  await sql`CREATE TABLE IF NOT EXISTS pp_push_subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT NOT NULL REFERENCES pp_clients(id) ON DELETE CASCADE,
    endpoint TEXT NOT NULL UNIQUE,
    p256dh TEXT NOT NULL,
    auth TEXT NOT NULL,
    user_agent TEXT NULL,
    platform TEXT NULL,
    active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_success_at TIMESTAMPTZ NULL,
    last_error TEXT NULL
  )`;
  await sql`CREATE INDEX IF NOT EXISTS pp_push_subscriptions_client_active_idx ON pp_push_subscriptions (client_id,active)`;
  await sql`CREATE TABLE IF NOT EXISTS pp_push_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_client_id BIGINT NULL REFERENCES pp_clients(id) ON DELETE SET NULL,
    target_mode TEXT NOT NULL DEFAULT 'client',
    title TEXT NOT NULL,
    body TEXT NOT NULL,
    click_url TEXT NULL,
    sent_count INTEGER NOT NULL DEFAULT 0,
    failed_count INTEGER NOT NULL DEFAULT 0,
    created_by_name TEXT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
  )`;
  await sql`CREATE TABLE IF NOT EXISTS pp_push_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_key TEXT NOT NULL UNIQUE,
    client_id BIGINT NOT NULL REFERENCES pp_clients(id) ON DELETE CASCADE,
    event_type TEXT NOT NULL,
    title TEXT NOT NULL,
    body TEXT NOT NULL,
    click_url TEXT NULL,
    attempts INTEGER NOT NULL DEFAULT 0,
    sent_count INTEGER NOT NULL DEFAULT 0,
    failed_count INTEGER NOT NULL DEFAULT 0,
    completed BOOLEAN NOT NULL DEFAULT false,
    last_attempt_at TIMESTAMPTZ NULL,
    sent_at TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
  )`;
  await sql`CREATE INDEX IF NOT EXISTS pp_push_events_client_created_idx ON pp_push_events (client_id,created_at DESC)`;
  schemaReady=true;
}

async function pushCryptoKey(env){
  const secret=text(env.BANK_SECRET_KEY)||text(env.PORTAL_SESSION_SECRET)||text(env.DATABASE_URL);
  if(!secret)throw Object.assign(new Error('Chave de proteção das notificações não configurada.'),{statusCode:503});
  const raw=await crypto.subtle.digest('SHA-256',enc.encode(`provedor-plus-push-v1|${secret}`));
  return crypto.subtle.importKey('raw',raw,{name:'AES-GCM'},false,['encrypt','decrypt']);
}
async function encryptVapid(env,value){const key=await pushCryptoKey(env),iv=crypto.getRandomValues(new Uint8Array(12)),cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,enc.encode(JSON.stringify(value)));return {v:1,iv:base64Url(iv),data:base64Url(new Uint8Array(cipher))}}
async function decryptVapid(env,record){if(!record?.iv||!record?.data)throw new Error('Chaves push inválidas.');const key=await pushCryptoKey(env),plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:base64UrlBytes(record.iv)},key,base64UrlBytes(record.data));return JSON.parse(new TextDecoder().decode(plain))}
async function vapidKeys(env,sql){
  const rows=await sql`SELECT value FROM pp_settings WHERE key=${VAPID_KEY} LIMIT 1`;
  if(rows?.[0]?.value)return decryptVapid(env,rows[0].value);
  const pair=await crypto.subtle.generateKey({name:'ECDSA',namedCurve:'P-256'},true,['sign','verify']),privateJWK=await crypto.subtle.exportKey('jwk',pair.privateKey),publicRaw=new Uint8Array(await crypto.subtle.exportKey('raw',pair.publicKey));
  const created={publicKey:base64Url(publicRaw),privateJWK,subject:'mailto:adrianomoreirausuarios@gmail.com'},encrypted=await encryptVapid(env,created),raw=JSON.stringify(encrypted),now=new Date().toISOString();
  const inserted=await sql`INSERT INTO pp_settings (key,value,updated_at) VALUES (${VAPID_KEY},${raw}::jsonb,${now}) ON CONFLICT (key) DO NOTHING RETURNING value`;
  if(inserted?.[0]?.value)return created;
  const existing=await sql`SELECT value FROM pp_settings WHERE key=${VAPID_KEY} LIMIT 1`;
  if(!existing?.[0]?.value)throw new Error('Não foi possível preparar as chaves de notificação.');
  return decryptVapid(env,existing[0].value);
}

async function portalKey(env){const secret=text(env.PORTAL_SESSION_SECRET)||text(env.DATABASE_URL);if(!secret)throw Object.assign(new Error('Sessão segura do portal não configurada.'),{statusCode:503});return crypto.subtle.importKey('raw',enc.encode(secret),{name:'HMAC',hash:'SHA-256'},false,['verify'])}
async function verifySession(token,env){
  const parts=text(token).split('.');if(parts.length!==2)throw Object.assign(new Error('Sessão do cliente inválida. Entre novamente.'),{statusCode:401});
  try{const key=await portalKey(env),ok=await crypto.subtle.verify('HMAC',key,base64UrlBytes(parts[1]),enc.encode(parts[0]));if(!ok)throw new Error('assinatura');const payload=JSON.parse(new TextDecoder().decode(base64UrlBytes(parts[0]))),clientId=Number(payload?.clientId)||0,exp=Number(payload?.exp)||0;if(!clientId||exp<=Date.now())throw new Error('expirada');return {clientId}}catch{throw Object.assign(new Error('Sessão do cliente expirada ou inválida. Entre novamente.'),{statusCode:401})}
}

function privateHost(host=''){const h=host.toLowerCase();if(!h||h==='localhost'||h==='::1'||h.endsWith('.local')||h.endsWith('.internal'))return true;if(/^127\./.test(h)||/^10\./.test(h)||/^192\.168\./.test(h)||/^169\.254\./.test(h))return true;const match=h.match(/^172\.(\d+)\./);if(match&&Number(match[1])>=16&&Number(match[1])<=31)return true;if(/^(fc|fd|fe80)/i.test(h))return true;return false}
function normalizeSubscription(value){
  const endpoint=text(value?.endpoint),p256dh=text(value?.keys?.p256dh),auth=text(value?.keys?.auth);let parsed;
  try{parsed=new URL(endpoint)}catch{throw Object.assign(new Error('Assinatura de notificação inválida.'),{statusCode:400})}
  if(parsed.protocol!=='https:'||privateHost(parsed.hostname)||!p256dh||!auth||endpoint.length>3000||p256dh.length>500||auth.length>300)throw Object.assign(new Error('Assinatura de notificação inválida.'),{statusCode:400});
  return {endpoint,p256dh,auth};
}
function normalizeClickUrl(value=''){const raw=text(value);if(!raw)return `${CLIENT_APP_ORIGIN}/`;if(raw.startsWith('/'))return `${CLIENT_APP_ORIGIN}${raw}`;try{const url=new URL(raw);return CLIENT_ORIGINS.has(url.origin)?url.toString():`${CLIENT_APP_ORIGIN}/`}catch{return `${CLIENT_APP_ORIGIN}/`}}
function notificationPayload(title,body,url,tag='fibra-plus'){return {title:text(title)||'Fibra+',body:text(body),icon:`${CLIENT_APP_ORIGIN}/icons/fibra-app-192.png?v=15`,badge:`${CLIENT_APP_ORIGIN}/icons/fibra-app-192.png?v=15`,tag:text(tag)||'fibra-plus',lang:'pt-BR',data:{url:normalizeClickUrl(url)}}}

async function sendOne(sql,row,vapid,payload){
  try{
    const built=await buildPushHTTPRequest({privateJWK:vapid.privateJWK,subscription:{endpoint:row.endpoint,keys:{p256dh:row.p256dh,auth:row.auth}},message:{payload,adminContact:vapid.subject||'mailto:adrianomoreirausuarios@gmail.com',options:{ttl:86400,urgency:'normal',topic:text(payload.tag).replace(/[^A-Za-z0-9_-]/g,'').slice(0,32)||'fibra-plus'}}});
    const response=await fetch(built.endpoint,{method:'POST',headers:built.headers,body:built.body,redirect:'manual'}),now=new Date().toISOString();
    if(response.ok){await sql`UPDATE pp_push_subscriptions SET active=true,last_success_at=${now},last_error=NULL,updated_at=${now} WHERE id=${Number(row.id)}`;return {ok:true}}
    const error=`Push HTTP ${response.status}`;if(response.status===404||response.status===410)await sql`UPDATE pp_push_subscriptions SET active=false,last_error=${error},updated_at=${now} WHERE id=${Number(row.id)}`;else await sql`UPDATE pp_push_subscriptions SET last_error=${error},updated_at=${now} WHERE id=${Number(row.id)}`;return {ok:false,error};
  }catch(error){const message=error instanceof Error?error.message:String(error),now=new Date().toISOString();try{await sql`UPDATE pp_push_subscriptions SET last_error=${message.slice(0,500)},updated_at=${now} WHERE id=${Number(row.id)}`}catch{}return {ok:false,error:message}}
}
async function sendRows(sql,rows,vapid,payload){let sent=0,failed=0;for(let start=0;start<rows.length;start+=10){const batch=rows.slice(start,start+10),results=await Promise.all(batch.map(row=>sendOne(sql,row,vapid,payload)));for(const result of results)result.ok?sent++:failed++}return {sent,failed,total:rows.length}}

async function sendAutomaticEvent(sql,env,event){
  const clientId=Number(event?.clientId)||0,key=text(event?.key),type=text(event?.type),title=text(event?.title).slice(0,90),message=text(event?.body).slice(0,500),clickUrl=normalizeClickUrl(event?.url||'/');
  if(!clientId||!key||!title||!message)return {skipped:true};
  const subscriptions=await sql`SELECT id,client_id,endpoint,p256dh,auth FROM pp_push_subscriptions WHERE client_id=${clientId} AND active=true ORDER BY id ASC`;
  if(!subscriptions.length)return {skipped:true,reason:'no-subscriptions'};
  await sql`INSERT INTO pp_push_events (event_key,client_id,event_type,title,body,click_url) VALUES (${key},${clientId},${type||'automatic'},${title},${message},${clickUrl}) ON CONFLICT (event_key) DO NOTHING`;
  const claimed=await sql`UPDATE pp_push_events SET attempts=attempts+1,last_attempt_at=now() WHERE event_key=${key} AND completed=false AND (last_attempt_at IS NULL OR last_attempt_at < now()-interval '2 minutes') RETURNING id`;
  if(!claimed?.[0]?.id)return {skipped:true,reason:'duplicate-or-running'};
  const vapid=await vapidKeys(env,sql),tag=`auto-${key.replace(/[^A-Za-z0-9_-]/g,'-').slice(-42)}`,payload=notificationPayload(title,message,clickUrl,tag),result=await sendRows(sql,subscriptions,vapid,payload),completed=result.sent>0,sentAt=completed?new Date().toISOString():null;
  await sql`UPDATE pp_push_events SET sent_count=${result.sent},failed_count=${result.failed},completed=${completed},sent_at=${sentAt} WHERE id=${Number(claimed[0].id)}`;
  if(completed)await sql`INSERT INTO pp_push_messages (target_client_id,target_mode,title,body,click_url,sent_count,failed_count,created_by_name) VALUES (${clientId},'client',${title},${message},${clickUrl},${result.sent},${result.failed},${`Automático · ${type||'notificação'}`})`;
  return result;
}

function invoiceAutomaticEvents(invoice,today,tomorrow,yesterday){
  const clientId=Number(invoice?.client_id)||0,id=text(invoice?.id),due=text(invoice?.due_date||invoice?.dueDate).slice(0,10),amount=invoiceCents(invoice),part=Math.max(0,Math.round(Number(invoice?.installment_number)||0)),total=Math.max(part,Math.round(Number(invoice?.installment_total)||part)),combined=invoice?.combined_billing===true,deferred=invoice?.bank_issue_deferred===true,events=[];
  if(!clientId||!id||deferred)return events;
  const paid=paidStatus(invoice?.status),open=invoiceOpen(invoice),createdAt=text(invoice?.created_at),paidAt=text(invoice?.paid_at);
  if(open&&recentTimestamp(createdAt,36)){
    let title='Nova fatura disponível',body=`Sua fatura de ${brl(amount)} foi gerada${due?` e vence em ${brDate(due)}`:''}.`;
    if(combined&&part){title='Nova cobrança disponível';body=`Sua mensalidade + parcela ${part}/${total} do acordo foi gerada no valor de ${brl(amount)}${due?` e vence em ${brDate(due)}`:''}.`}
    else if(part){title='Parcela do acordo disponível';body=`A parcela ${part}/${total} do seu acordo está disponível no valor de ${brl(amount)}${due?` e vence em ${brDate(due)}`:''}.`}
    events.push({key:`invoice-created:${id}`,clientId,type:'fatura gerada',title,body,url:'/#faturas'});
  }
  if(open&&due===tomorrow){
    let title='Sua fatura vence amanhã',body=`Sua fatura de ${brl(amount)} vence amanhã, ${brDate(due)}.`;
    if(combined&&part){title='Mensalidade + acordo vencem amanhã';body=`Sua mensalidade + parcela ${part}/${total} do acordo, no total de ${brl(amount)}, vencem amanhã.`}
    else if(part){title='Parcela do acordo vence amanhã';body=`A parcela ${part}/${total} do seu acordo, no valor de ${brl(amount)}, vence amanhã.`}
    events.push({key:`due-tomorrow:${id}:${due}`,clientId,type:'vencimento próximo',title,body,url:'/#faturas'});
  }
  if(open&&due===yesterday){
    let title='Fatura vencida',body=`Sua fatura de ${brl(amount)} venceu ontem. Consulte a cobrança na Área do Cliente.`;
    if(combined&&part){title='Cobrança vencida';body=`Sua mensalidade + parcela ${part}/${total} do acordo venceram ontem. Consulte a cobrança na Área do Cliente.`}
    else if(part){title='Parcela do acordo vencida';body=`A parcela ${part}/${total} do seu acordo venceu ontem. Consulte a cobrança na Área do Cliente.`}
    events.push({key:`overdue:${id}:${due}`,clientId,type:'fatura vencida',title,body,url:'/#faturas'});
  }
  if(paid&&paidAt&&recentTimestamp(paidAt,36)){
    let body=`Recebemos seu pagamento de ${brl(amount)}. Obrigado!`;
    if(combined&&part)body=`Pagamento confirmado: ${brl(amount)} da mensalidade + parcela ${part}/${total} do acordo.`;
    else if(part)body=`Pagamento confirmado: parcela ${part}/${total} do acordo no valor de ${brl(amount)}.`;
    events.push({key:`payment:${id}:${paidAt}`,clientId,type:'pagamento confirmado',title:'Pagamento confirmado',body,url:'/#faturas'});
  }
  return events;
}

function cashbackAutomaticEvents(state){
  const transactions=Array.isArray(state?.cashback_transactions)?state.cashback_transactions:[],events=[];
  for(const item of transactions){
    if(text(item?.source)!=='pix_paid'||text(item?.type).toLowerCase()!=='credit'||!recentTimestamp(item?.created_at,36))continue;
    const clientId=Number(item?.client_id)||0,amount=Math.max(0,Math.round(Number(item?.amount_cents)||0)),balance=Math.max(0,Math.round(Number(item?.balance_after_cents)||0)),id=text(item?.id)||`${item?.invoice_id||'pix'}:${item?.created_at||''}`;
    if(!clientId||!amount)continue;
    events.push({key:`cashback:${id}`,clientId,type:'cashback recebido',title:'Cashback recebido',body:`Você recebeu ${brl(amount)} de cashback. Seu saldo agora é ${brl(balance)}.`,url:'/#cashback'});
  }
  return events;
}

async function scanAutomaticEvents(env){
  if(!env?.DATABASE_URL)return {scanned:false};
  const sql=neon(env.DATABASE_URL);await ensurePushTables(sql);const state=await loadState(sql),today=brazilDateKey(),tomorrow=addDaysKey(today,1),yesterday=addDaysKey(today,-1),events=[];
  for(const invoice of Array.isArray(state?.invoices)?state.invoices:[])events.push(...invoiceAutomaticEvents(invoice,today,tomorrow,yesterday));
  events.push(...cashbackAutomaticEvents(state));
  const unique=[...new Map(events.map(event=>[event.key,event])).values()].slice(0,250);let sent=0,failed=0,skipped=0;
  for(const event of unique){try{const result=await sendAutomaticEvent(sql,env,event);if(result?.skipped)skipped++;else{sent+=Number(result?.sent)||0;failed+=Number(result?.failed)||0}}catch(error){failed++;console.error('Provedor Plus: falha ao enviar notificação automática.',event?.type,error)}}
  return {scanned:true,events:unique.length,sent,failed,skipped};
}

async function shouldScanAfterRequest(request){
  if(request.method!=='POST')return false;
  const path=new URL(request.url).pathname;
  if(path==='/api/cloud-state'||path==='/api/bank-proxy')return true;
  if(path!=='/api/customer-portal')return false;
  let action='';try{const body=await request.clone().json();action=text(body?.action).toLowerCase()}catch{}
  return !['login','refresh','connection-test','negotiation-options','negotiation-preview','cashback-statement'].includes(action);
}

async function requirePanelAdmin(request,env,ctx){
  const origin=new URL(request.url).origin,headers=new Headers(request.headers);headers.set('Content-Type','application/json');const authRequest=new Request(`${origin}/api/auth`,{method:'POST',headers,body:JSON.stringify({action:'status'})}),response=await coreWorker.fetch(authRequest,env,ctx);let body={};try{body=await response.json()}catch{}const user=body?.data?.user;if(!response.ok||!body?.ok||body?.data?.authenticated!==true)throw Object.assign(new Error('Sessão expirada ou não autenticada.'),{statusCode:401});if(text(user?.role).toLowerCase()!=='admin')throw Object.assign(new Error('Somente o administrador pode enviar notificações.'),{statusCode:403});return user}

async function handleCustomerPush(request,env,ctx){
  const cors=clientCors(request);if(request.method==='OPTIONS')return new Response(null,{status:204,headers:cors});if(request.method!=='POST')return json({ok:false,error:'Método não permitido.'},405,cors);
  const origin=text(request.headers.get('origin'));if(!CLIENT_ORIGINS.has(origin))return json({ok:false,error:'Origem não autorizada.'},403,cors);
  try{
    if(!env.DATABASE_URL)throw Object.assign(new Error('Conexão com o Provedor Plus não configurada.'),{statusCode:503});let body={};try{body=await request.json()}catch{}const action=text(body?.action),data=body?.data||{},sql=neon(env.DATABASE_URL);await ensurePushTables(sql);
    if(action==='config'){const vapid=await vapidKeys(env,sql);return json({ok:true,data:{publicKey:vapid.publicKey,supported:true}},200,cors)}
    const session=await verifySession(data?.session,env),clientId=session.clientId;
    if(action==='subscribe'){
      const subscription=normalizeSubscription(data?.subscription),ua=text(data?.userAgent||request.headers.get('user-agent')).slice(0,800),platform=text(data?.platform).slice(0,120),now=new Date().toISOString();
      await sql`INSERT INTO pp_push_subscriptions (client_id,endpoint,p256dh,auth,user_agent,platform,active,created_at,updated_at) VALUES (${clientId},${subscription.endpoint},${subscription.p256dh},${subscription.auth},${ua||null},${platform||null},true,${now},${now}) ON CONFLICT (endpoint) DO UPDATE SET client_id=EXCLUDED.client_id,p256dh=EXCLUDED.p256dh,auth=EXCLUDED.auth,user_agent=EXCLUDED.user_agent,platform=EXCLUDED.platform,active=true,updated_at=EXCLUDED.updated_at,last_error=NULL`;
      const rows=await sql`SELECT id,endpoint,p256dh,auth FROM pp_push_subscriptions WHERE client_id=${clientId} AND endpoint=${subscription.endpoint} AND active=true LIMIT 1`,vapid=await vapidKeys(env,sql),payload=notificationPayload('Notificações Fibra+ ativadas','Pronto. Você receberá avisos importantes da sua conta diretamente neste dispositivo.','/','fibra-ativada');
      if(rows?.[0]){const task=sendRows(sql,rows,vapid,payload);if(typeof ctx?.waitUntil==='function')ctx.waitUntil(task);else await task}
      const count=await sql`SELECT COUNT(*)::int AS total FROM pp_push_subscriptions WHERE client_id=${clientId} AND active=true`;
      return json({ok:true,data:{active:true,devices:Number(count?.[0]?.total)||1}},200,cors);
    }
    if(action==='unsubscribe'){
      const endpoint=text(data?.endpoint);if(endpoint)await sql`UPDATE pp_push_subscriptions SET active=false,updated_at=now() WHERE client_id=${clientId} AND endpoint=${endpoint}`;else await sql`UPDATE pp_push_subscriptions SET active=false,updated_at=now() WHERE client_id=${clientId}`;
      return json({ok:true,data:{active:false}},200,cors);
    }
    if(action==='status'){
      const endpoint=text(data?.endpoint),rows=endpoint?await sql`SELECT COUNT(*)::int AS total FROM pp_push_subscriptions WHERE client_id=${clientId} AND endpoint=${endpoint} AND active=true`:await sql`SELECT COUNT(*)::int AS total FROM pp_push_subscriptions WHERE client_id=${clientId} AND active=true`;
      return json({ok:true,data:{active:(Number(rows?.[0]?.total)||0)>0,devices:Number(rows?.[0]?.total)||0}},200,cors);
    }
    throw Object.assign(new Error('Ação de notificação não permitida.'),{statusCode:400});
  }catch(error){return json({ok:false,error:error instanceof Error?error.message:String(error)},Number(error?.statusCode)||500,cors)}
}

async function resolveTargetClient(sql,identifier){const raw=text(identifier),doc=digits(raw),rows=await sql`SELECT id,name,contract_number,document FROM pp_clients WHERE contract_number=${raw} OR regexp_replace(COALESCE(contract_number,''),'[^0-9]','','g')=${doc} OR regexp_replace(COALESCE(document,''),'[^0-9]','','g')=${doc} ORDER BY id ASC LIMIT 1`;return rows?.[0]||null}
async function handleAdminPush(request,env,ctx){
  if(request.method!=='POST')return json({ok:false,error:'Método não permitido.'},405);
  try{
    const user=await requirePanelAdmin(request,env,ctx);if(!env.DATABASE_URL)throw Object.assign(new Error('Conexão com o Neon não configurada.'),{statusCode:503});let body={};try{body=await request.json()}catch{}const action=text(body?.action),data=body?.data||{},sql=neon(env.DATABASE_URL);await ensurePushTables(sql);
    if(action==='stats'){
      const stats=await sql`SELECT COUNT(*) FILTER (WHERE active)::int AS devices,COUNT(DISTINCT client_id) FILTER (WHERE active)::int AS clients FROM pp_push_subscriptions`,history=await sql`SELECT id,target_mode,title,body,sent_count,failed_count,created_by_name,created_at FROM pp_push_messages ORDER BY id DESC LIMIT 10`;
      return json({ok:true,data:{devices:Number(stats?.[0]?.devices)||0,clients:Number(stats?.[0]?.clients)||0,history:history||[]}});
    }
    if(action==='send'){
      const title=text(data?.title).slice(0,90),message=text(data?.body).slice(0,500),mode=data?.mode==='all'?'all':'client',clickUrl=normalizeClickUrl(data?.url);if(!title||!message)throw Object.assign(new Error('Informe o título e a mensagem da notificação.'),{statusCode:400});let targetClient=null,subscriptions=[];
      if(mode==='all')subscriptions=await sql`SELECT id,client_id,endpoint,p256dh,auth FROM pp_push_subscriptions WHERE active=true ORDER BY id ASC`;
      else{targetClient=await resolveTargetClient(sql,data?.identifier);if(!targetClient)throw Object.assign(new Error('Cliente não encontrado pelo CPF/CNPJ ou contrato informado.'),{statusCode:404});subscriptions=await sql`SELECT id,client_id,endpoint,p256dh,auth FROM pp_push_subscriptions WHERE client_id=${Number(targetClient.id)} AND active=true ORDER BY id ASC`;}
      if(!subscriptions.length)throw Object.assign(new Error(mode==='all'?'Nenhum dispositivo autorizou notificações ainda.':'Este cliente ainda não autorizou notificações em nenhum dispositivo.'),{statusCode:409});
      const vapid=await vapidKeys(env,sql),payload=notificationPayload(title,message,clickUrl,`fibra-${Date.now().toString(36)}`),result=await sendRows(sql,subscriptions,vapid,payload),createdBy=text(user?.name)||'Administrador';
      await sql`INSERT INTO pp_push_messages (target_client_id,target_mode,title,body,click_url,sent_count,failed_count,created_by_name) VALUES (${targetClient?Number(targetClient.id):null},${mode},${title},${message},${clickUrl},${result.sent},${result.failed},${createdBy})`;
      return json({ok:true,data:{...result,targetClient:targetClient?{id:Number(targetClient.id),name:text(targetClient.name),contract:text(targetClient.contract_number)}:null}});
    }
    throw Object.assign(new Error('Ação administrativa de notificação não permitida.'),{statusCode:400});
  }catch(error){return json({ok:false,error:error instanceof Error?error.message:String(error)},Number(error?.statusCode)||500)}
}

async function handleCoreFetch(request,env,ctx){
  const scan=env?.DATABASE_URL?await shouldScanAfterRequest(request):false;
  const response=await coreWorker.fetch(request,env,ctx);
  if(scan&&response?.ok){const task=scanAutomaticEvents(env).catch(error=>console.error('Provedor Plus: falha na verificação automática de notificações após ação.',error));if(typeof ctx?.waitUntil==='function')ctx.waitUntil(task)}
  return response;
}

export default {
  fetch(request,env,ctx){const path=new URL(request.url).pathname;if(path===CLIENT_PUSH_PATH)return handleCustomerPush(request,env,ctx);if(path===ADMIN_PUSH_PATH)return handleAdminPush(request,env,ctx);return handleCoreFetch(request,env,ctx)},
  scheduled(controller,env,ctx){const result=coreWorker.scheduled(controller,env,ctx);if(env?.DATABASE_URL&&typeof ctx?.waitUntil==='function')ctx.waitUntil(scanAutomaticEvents(env).catch(error=>console.error('Provedor Plus: falha no ciclo automático de notificações.',error)));return result}
};
