import { clone, collections, invoiceCents, mergedClients, mergedRouters, money, nextId, text } from './model.js';
import { createForms } from './panel-forms.js';
import { createViews } from './panel-views.js';
import { hasPermission, loginTemplate, moneyToCents, NAV, navAllowed, shellTemplate, esc } from './ui-kit.js';

export function createPanel(root,api){
  const {authApi,stateApi,dataApi,bankApi,mikrotikApi,protocolApi,pushApi,storiesApi}=api;
  let configured=true,user=null,state={},stateUpdatedAt='',remoteClients=[],remoteRouters=[],employees=[],protocols=[],bankSafe={},pushStats={},stories=[],currentView='dashboard',busy=false;
  const clients=()=>mergedClients(state,remoteClients),routers=()=>mergedRouters(state,remoteRouters),data=()=>collections(state);
  const byClient=(id)=>clients().find((x)=>Number(x.id)===Number(id)),byRouter=(id)=>routers().find((x)=>Number(x.id)===Number(id)),byPlan=(id)=>data().plans.find((x)=>Number(x.id)===Number(id)),byInvoice=(id)=>data().invoices.find((x)=>String(x.id)===String(id));
  const context=()=>({user,state,clients:clients(),routers:routers(),data:data(),protocols,employees,bankSafe,pushStats,stories,byClient,byRouter,byPlan,byInvoice});

  function toast(message,kind='success'){const node=document.createElement('div');node.className=`toast ${kind}`;node.textContent=message;root.querySelector('#toast-root')?.append(node);setTimeout(()=>node.remove(),4500)}
  function modal(title,body,wide=false){const host=root.querySelector('#modal-root');host.innerHTML=`<div class="modal-backdrop"><section class="modal${wide?' wide':''}" role="dialog" aria-modal="true"><header><div><span class="eyebrow">Provedor Plus</span><h3>${esc(title)}</h3></div><button class="modal-x" type="button" data-action="close-modal">×</button></header><div class="modal-body">${body}</div></section></div>`}
  function closeModal(){const host=root.querySelector('#modal-root');if(host)host.innerHTML=''}
  function setBusy(value){busy=value;root.querySelectorAll('button,input,select,textarea').forEach((el)=>{if(el.closest('.modal')||value)el.disabled=value})}
  async function task(fn,success='Concluído.',keepModal=false){if(busy)return;setBusy(true);try{await fn();if(success)toast(success);if(!keepModal)closeModal();await loadAll();render()}catch(error){toast(error.message||String(error),'error')}finally{setBusy(false)}}
  function addAudit(next,action,entity,entityId,detail=''){const item={id:crypto.randomUUID(),action,entity,entity_id:entityId??null,description:detail,created_at:new Date().toISOString(),created_by_id:user?.id||null,created_by_name:user?.name||user?.email||'Painel'};next.audit=[item,...(Array.isArray(next.audit)?next.audit:[])].slice(0,1500)}
  async function saveState(next,action='',entity='',entityId=null,detail=''){if(action)addAudit(next,action,entity,entityId,detail);const result=await stateApi.save(next,stateUpdatedAt);state=result?.state||next;stateUpdatedAt=result?.updated_at||new Date().toISOString();return state}
  async function mutate(mutator,action,entity,entityId,detail=''){const next=clone(state);await mutator(next);return saveState(next,action,entity,entityId,detail)}

  async function loadAll(){
    const stateResult=await stateApi.load();state=stateResult?.state&&typeof stateResult.state==='object'?stateResult.state:{};stateUpdatedAt=stateResult?.updated_at||'';
    const results=await Promise.allSettled([dataApi.clients(),dataApi.routers(),protocolApi.list(null,200),user?.role==='admin'?authApi.employees():Promise.resolve([]),user?.role==='admin'?bankApi.safe():Promise.resolve({}),user?.role==='admin'?pushApi.stats():Promise.resolve({}),user?.role==='admin'?storiesApi.list():Promise.resolve({stories:[]})]);
    remoteClients=results[0].status==='fulfilled'?(results[0].value||[]):[];remoteRouters=results[1].status==='fulfilled'?(results[1].value||[]):[];protocols=results[2].status==='fulfilled'?(results[2].value||[]):[];employees=results[3].status==='fulfilled'?(results[3].value||[]):[];bankSafe=results[4].status==='fulfilled'?(results[4].value||{}):{};pushStats=results[5].status==='fulfilled'?(results[5].value||{}):{};stories=results[6].status==='fulfilled'?(results[6].value?.stories||[]):[];
  }
  function render(){const content=root.querySelector('#content');if(!content)return;const label=NAV.find(([id])=>id===currentView)?.[1]||'Visão geral';root.querySelector('#page-title').textContent=label;root.querySelectorAll('[data-view]').forEach((b)=>b.classList.toggle('active',b.dataset.view===currentView));const views=createViews(context());content.innerHTML=(views[currentView]||views.dashboard)()}
  function forms(){return createForms(context())}
  async function routerWithSecret(router){const secret=await dataApi.routerSecret(router.id);return {...router,password:secret?.password||''}}

  async function saveClientFromForm(form){
    const fd=new FormData(form),id=Number(fd.get('id'))||0,plan=byPlan(fd.get('plan_id')),existing=id?byClient(id):{};
    const payload={...existing,id:id||undefined,name:fd.get('name'),document:fd.get('document'),contract_number:fd.get('contract_number'),email:fd.get('email'),phone:fd.get('phone'),address:fd.get('address'),city:fd.get('city'),state:String(fd.get('state')||'').toUpperCase(),zip_code:fd.get('zip_code'),plan_id:Number(fd.get('plan_id'))||null,plan:plan?.name||'',due_day:Number(fd.get('due_day'))||10,status:fd.get('status'),router_id:Number(fd.get('router_id'))||null,connection_type:fd.get('connection_type'),pppoe_username:fd.get('pppoe_username'),pppoe_password:fd.get('pppoe_password'),mikrotik_profile:fd.get('mikrotik_profile'),ip:fd.get('ip'),mac_address:fd.get('mac_address'),auto_block:fd.get('auto_block')==='on',block_after_days:Number(fd.get('block_after_days'))||7};
    if(!payload.pppoe_password)delete payload.pppoe_password;const saved=await dataApi.clientSave(payload),extra={billing_bank_provider:fd.get('billing_bank_provider'),notes:fd.get('notes'),address_number:fd.get('address_number'),neighborhood:fd.get('neighborhood'),complement:fd.get('complement'),installation_date:fd.get('installation_date')};
    await mutate((next)=>{const list=Array.isArray(next.clients)?[...next.clients]:[],pos=list.findIndex((x)=>Number(x.id)===Number(saved.id)),merged={...(pos>=0?list[pos]:{}),...saved,...extra,plan_id:payload.plan_id,plan:payload.plan};if(pos>=0)list[pos]=merged;else list.push(merged);next.clients=list},id?'cliente_editado':'cliente_criado','client',saved.id,saved.name);return saved;
  }
  async function saveInvoiceFromForm(form){const fd=new FormData(form),rawId=fd.get('id'),existing=rawId?byInvoice(rawId):null,clientId=Number(fd.get('client_id')),client=byClient(clientId);if(!client)throw new Error('Selecione um cliente.');const amount=moneyToCents(fd.get('amount'));if(!amount)throw new Error('Informe um valor maior que zero.');const invoice={...(existing||{}),id:existing?.id??nextId(data().invoices,state?.seq?.invoices),client_id:clientId,due_date:fd.get('due_date'),amount_cents:amount,reference:fd.get('reference')||String(fd.get('due_date')).slice(0,7),competency:fd.get('reference')||String(fd.get('due_date')).slice(0,7),billing_type:fd.get('billing_type'),description:fd.get('description'),bank_provider:fd.get('bank_provider')||existing?.bank_provider||'',status:fd.get('status')||'Pendente',created_at:existing?.created_at||new Date().toISOString(),updated_at:new Date().toISOString(),cashback_eligible:existing?.cashback_eligible!==false};await mutate((next)=>{const list=Array.isArray(next.invoices)?[...next.invoices]:[],pos=list.findIndex((x)=>String(x.id)===String(invoice.id));if(pos>=0)list[pos]=invoice;else list.push(invoice);next.invoices=list;next.seq={...(next.seq||{}),invoices:Math.max(Number(next.seq?.invoices)||0,Number(invoice.id)||0)}},existing?'mensalidade_editada':'mensalidade_criada','invoice',invoice.id,`${client.name} · ${money(amount,true)}`)}

  const permissionMap={'go-invoices':'billing','new-client':'clients','edit-client':'clients','client-block':'network','client-unblock':'network','client-connection':'network','new-plan':'plans','edit-plan':'plans','delete-plan':'plans','new-invoice':'billing','edit-invoice':'billing','issue-invoice':'billing','sync-invoice':'billing','pay-invoice':'billing','cancel-invoice':'billing','cashback-rules':'finance','cashback-adjust':'finance','export-finance':'finance','new-router':'network','edit-router':'network','test-router':'network','sync-router':'network','profiles-router':'network','delete-router':'network','new-protocol':'tickets','close-protocol':'tickets'};
  const adminActions=new Set(['new-employee','edit-employee','toggle-employee','new-story','edit-story','toggle-story','delete-story','config-efi','config-mp','test-efi','test-mp','webhooks-efi']);
  async function handleClick(event){
    if(event.target.classList?.contains('modal-backdrop')){closeModal();return}const target=event.target.closest('[data-action],[data-view]');if(!target)return;
    if(target.dataset.view){if(!navAllowed(user,target.dataset.view)){toast('Seu usuário não possui permissão para esta área.','error');return}currentView=target.dataset.view;root.querySelector('#sidebar')?.classList.remove('open');render();return}
    const action=target.dataset.action,id=target.dataset.id;if(permissionMap[action]&&!hasPermission(user,permissionMap[action])){toast('Seu usuário não possui permissão para esta operação.','error');return}if(adminActions.has(action)&&String(user?.role||'').toLowerCase()!=='admin'){toast('Somente o administrador pode realizar esta operação.','error');return}
    if(action==='menu'){root.querySelector('#sidebar')?.classList.toggle('open');return}if(action==='close-modal'){closeModal();return}if(action==='refresh'){await task(async()=>{},'Dados atualizados.');return}if(action==='logout'){await authApi.logout();user=null;await showLogin();return}if(action==='go-invoices'){currentView='invoices';render();return}
    const f=forms();if(action==='new-client'||action==='edit-client'){modal(id?'Editar cliente':'Novo cliente',f.clientForm(id?byClient(id):{}),true);return}if(action==='new-plan'||action==='edit-plan'){modal(id?'Editar plano':'Novo plano',f.planForm(id?byPlan(id):{}));return}if(action==='new-invoice'||action==='edit-invoice'){modal(id?'Editar mensalidade':'Nova mensalidade',f.invoiceForm(id?byInvoice(id):{}),true);return}if(action==='cashback-rules'){modal('Regras de cashback',f.cashbackRulesForm());return}if(action==='cashback-adjust'){modal('Movimentar cashback',f.cashbackAdjustForm());return}if(action==='new-router'||action==='edit-router'){modal(id?'Editar MikroTik':'Novo MikroTik',f.routerForm(id?byRouter(id):{}));return}if(action==='new-protocol'){modal('Abrir chamado',f.protocolForm());return}if(action==='new-employee'||action==='edit-employee'){modal(id?'Editar funcionário':'Novo funcionário',f.employeeForm(id?employees.find((x)=>Number(x.id)===Number(id)):{}),true);return}if(action==='new-story'||action==='edit-story'){modal(id?'Editar publicidade':'Nova publicidade',f.storyForm(id?stories.find((x)=>String(x.id)===String(id)):{}),true);return}if(action==='config-efi'){modal('Configurar Efí Bank',f.efiForm(),true);return}if(action==='config-mp'){modal('Configurar Mercado Pago',f.mpForm(),true);return}
    if(action==='delete-plan'){const plan=byPlan(id),used=clients().some((c)=>Number(c.plan_id)===Number(id));if(used){toast('Este plano está vinculado a clientes. Inative ou altere os clientes antes de excluir.','error');return}if(!confirm(`Excluir o plano ${plan?.name||id}?`))return;await task(()=>mutate((next)=>{next.plans=(next.plans||[]).filter((x)=>Number(x.id)!==Number(id))},'plano_excluido','plan',id,plan?.name),'Plano excluído.');return}
    if(action==='client-block'||action==='client-unblock'||action==='client-connection'){const client=byClient(id),router=byRouter(client?.router_id);if(!client||!router){toast('Cliente sem MikroTik configurado.','error');return}await task(async()=>{const secure=await routerWithSecret(router),mtAction=action==='client-block'?'client.block':action==='client-unblock'?'client.unblock':'client.status',result=await mikrotikApi.run(mtAction,secure,client);if(action==='client-connection'){modal('Diagnóstico da conexão',`<div class="diagnostic"><h4>${esc(client.name)}</h4><pre>${esc(JSON.stringify(result,null,2))}</pre></div>`,true);return}const nextStatus=action==='client-block'?'Bloqueado':'Ativo',saved=await dataApi.clientSave({...client,status:nextStatus});await mutate((next)=>{const list=Array.isArray(next.clients)?[...next.clients]:[],pos=list.findIndex((x)=>Number(x.id)===Number(client.id));if(pos>=0)list[pos]={...list[pos],...saved,status:nextStatus,mikrotik_last_sync:new Date().toISOString()};next.clients=list},action==='client-block'?'cliente_bloqueado':'cliente_liberado','client',client.id,client.name)},action==='client-connection'?'Diagnóstico concluído.':action==='client-block'?'Cliente bloqueado no MikroTik.':'Cliente liberado no MikroTik.',action==='client-connection');return}
    if(['test-router','sync-router','profiles-router'].includes(action)){const router=byRouter(id);await task(async()=>{const secure=await routerWithSecret(router),mtAction=action==='profiles-router'?'router.profiles':action==='sync-router'?'router.sync':'router.test',result=await mikrotikApi.run(mtAction,secure);if(action==='sync-router')await dataApi.routerSave({...router,last_status:'Conectado',last_sync:new Date().toISOString()});modal(action==='profiles-router'?'Perfis PPP':'Resultado do MikroTik',`<pre class="result-pre">${esc(JSON.stringify(result,null,2))}</pre>`,true)},'',true);return}
    if(action==='delete-router'){const router=byRouter(id),used=clients().some((c)=>Number(c.router_id)===Number(id));if(used){toast('Este MikroTik está vinculado a clientes. Remova os vínculos antes de excluir.','error');return}if(!confirm(`Excluir ${router?.name||'MikroTik'}?`))return;await task(async()=>{await dataApi.routerSecretDelete(id);await dataApi.routerDelete(id);await mutate((next)=>{next.routers=(next.routers||[]).filter((x)=>Number(x.id)!==Number(id))},'mikrotik_excluido','router',id,router?.name)},'MikroTik excluído.');return}
    if(action==='close-protocol'){if(!confirm(`Concluir o protocolo ${id}?`))return;await task(async()=>{await protocolApi.close(id,'Concluído');await mutate(()=>{},'chamado_concluido','protocol',id,id)},'Chamado concluído.');return}
    if(action==='toggle-employee'){const emp=employees.find((x)=>Number(x.id)===Number(id));await task(async()=>{await authApi.employeeToggle(id,emp?.active===false);await mutate(()=>{},emp?.active===false?'funcionario_ativado':'funcionario_desativado','employee',id,emp?.name)},'Acesso atualizado.');return}
    if(action==='toggle-story'){const story=stories.find((x)=>String(x.id)===String(id));await task(async()=>{await storiesApi.toggle(id,story?.active===false);await mutate(()=>{},'publicidade_alterada','story',id,story?.title)},'Publicidade atualizada.');return}if(action==='delete-story'){if(!confirm('Excluir esta publicidade?'))return;await task(async()=>{await storiesApi.remove(id);await mutate(()=>{},'publicidade_excluida','story',id)},'Publicidade excluída.');return}
    if(action==='export-finance'){const rows=[['ID','Cliente','Referência','Vencimento','Valor','Status','Forma','Pago em']];for(const x of data().invoices)rows.push([x.id,byClient(x.client_id)?.name||`Cliente #${x.client_id}`,x.reference||x.competency||'',x.due_date||'',(invoiceCents(x)/100).toFixed(2),x.status||'',x.payment_method||'',x.paid_at||'']);const csv=rows.map((row)=>row.map((v)=>`"${String(v??'').replace(/"/g,'""')}"`).join(';')).join('\n'),blob=new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`provedor-plus-financeiro-${new Date().toISOString().slice(0,10)}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Relatório financeiro exportado.');return}
    if(action==='test-efi'){await task(()=>bankApi.testEfi(),'Conexão Efí confirmada.');return}if(action==='test-mp'){await task(()=>bankApi.testMercadoPago(),'Conexão Mercado Pago confirmada.');return}if(action==='webhooks-efi'){await task(()=>bankApi.configureEfiWebhooks(),'Webhooks Efí configurados.');return}
    if(['issue-invoice','sync-invoice','pay-invoice','cancel-invoice'].includes(action)){const inv=byInvoice(id),client=byClient(inv?.client_id);if(!inv||!client){toast('Mensalidade ou cliente não encontrado.','error');return}if(action==='pay-invoice'){if(!confirm('Dar baixa manual nesta mensalidade?'))return;await task(()=>mutate((next)=>{const x=(next.invoices||[]).find((i)=>String(i.id)===String(id));Object.assign(x,{status:'Pago',payment_method:'Baixa manual',paid_by:user?.name||'Painel',paid_at:new Date().toISOString()})},'mensalidade_baixada','invoice',id,client.name),'Mensalidade baixada.');return}await task(async()=>{const vault=await bankApi.vault(),provider=inv.bank_provider||state?.banks?.defaultProvider||((vault?.efi?.enabled)?'efi':(vault?.mercadoPago?.enabled?'mercadoPago':''));if(!provider)throw new Error('Defina um banco emissor em Integrações.');const payload={action:action==='issue-invoice'?'issue':action==='sync-invoice'?'sync':'cancel',provider,invoice:{...inv,bank_provider:provider,client_name:client.name,client_contract_number:client.contract_number},client,efi:vault?.efi||{},mercadoPago:vault?.mercadoPago||{}},result=await bankApi.proxy(payload);await mutate((next)=>{const x=(next.invoices||[]).find((i)=>String(i.id)===String(id));if(!x)return;Object.assign(x,result||{});if(action==='cancel-invoice')x.status='Cancelado';if(action==='sync-invoice'&&(result?.paidAt||/paid|pago|settled/i.test(text(result?.bank_status))))Object.assign(x,{status:'Pago',paid_at:result?.paidAt||x.paid_at||new Date().toISOString()})},action==='issue-invoice'?'cobranca_emitida':action==='sync-invoice'?'cobranca_sincronizada':'cobranca_cancelada','invoice',id,`${client.name} · ${provider}`)},action==='issue-invoice'?'Cobrança emitida.':action==='sync-invoice'?'Cobrança sincronizada.':'Cobrança cancelada.');return}
  }

  async function handleSubmit(event){const form=event.target.closest('form');if(!form)return;event.preventDefault();
    if(form.id==='login-form'){const fd=new FormData(form),error=form.querySelector('#login-error');try{const result=configured?await authApi.login(fd.get('login'),fd.get('password')):await authApi.setup(fd.get('name'),fd.get('login'),fd.get('password'));user=result.user;await showShell()}catch(e){error.textContent=e.message}return}
    if(form.id==='client-form'){await task(()=>saveClientFromForm(form),'Cliente salvo e sincronizado.');return}
    if(form.id==='plan-form'){await task(async()=>{const fd=new FormData(form),id=Number(fd.get('id'))||nextId(data().plans,state?.seq?.plans),existing=byPlan(id),plan={...(existing||{}),id,name:fd.get('name'),speed:fd.get('speed'),price_cents:moneyToCents(fd.get('price')),mikrotik_profile:fd.get('mikrotik_profile'),download_mbps:Number(fd.get('download_mbps'))||0,upload_mbps:Number(fd.get('upload_mbps'))||0,active:fd.get('active')==='on',description:fd.get('description'),updated_at:new Date().toISOString()};await mutate((next)=>{const list=Array.isArray(next.plans)?[...next.plans]:[],pos=list.findIndex((x)=>Number(x.id)===id);if(pos>=0)list[pos]=plan;else list.push(plan);next.plans=list;next.seq={...(next.seq||{}),plans:Math.max(Number(next.seq?.plans)||0,id)}},existing?'plano_editado':'plano_criado','plan',id,plan.name)},'Plano salvo.');return}
    if(form.id==='invoice-form'){await task(()=>saveInvoiceFromForm(form),'Mensalidade salva.');return}
    if(form.id==='cashback-rules-form'){await task(async()=>{const fd=new FormData(form);await mutate((next)=>{next.settings={...(next.settings||{}),cashback_enabled:fd.get('cashback_enabled')==='on',cashback_mode:fd.get('cashback_mode')==='fixed'?'fixed':'percent',cashback_rate:Math.max(0,Math.min(100,Number(fd.get('cashback_rate'))||0)),cashback_fixed_cents:moneyToCents(fd.get('cashback_fixed'))}},'cashback_regras_alteradas','settings','cashback')},'Regras de cashback salvas.');return}
    if(form.id==='cashback-adjust-form'){await task(async()=>{const fd=new FormData(form);await dataApi.cashbackAdjust({clientId:Number(fd.get('client_id')),operation:fd.get('operation'),amount_cents:moneyToCents(fd.get('amount')),reason:fd.get('reason')})},'Carteira atualizada.');return}
    if(form.id==='router-form'){await task(async()=>{const fd=new FormData(form),id=Number(fd.get('id'))||undefined,existing=id?byRouter(id):{},saved=await dataApi.routerSave({...existing,id,name:fd.get('name'),host:fd.get('host'),port:Number(fd.get('port'))||443,username:fd.get('username'),active:fd.get('active')==='on',allow_self_signed:fd.get('allow_self_signed')==='on'});if(fd.get('password'))await dataApi.routerSecretSave(saved.id,fd.get('password'));await mutate((next)=>{const list=Array.isArray(next.routers)?[...next.routers]:[],pos=list.findIndex((x)=>Number(x.id)===Number(saved.id));if(pos>=0)list[pos]={...list[pos],...saved};else list.push(saved);next.routers=list},id?'mikrotik_editado':'mikrotik_criado','router',saved.id,saved.name)},'MikroTik salvo.');return}
    if(form.id==='protocol-form'){await task(async()=>{const fd=new FormData(form),created=await protocolApi.create({clientId:Number(fd.get('clientId'))||null,category:fd.get('category'),subject:fd.get('subject'),status:fd.get('status'),details:{description:text(fd.get('details'))}});await mutate(()=>{},'chamado_aberto','protocol',created.protocol,fd.get('subject'))},'Chamado aberto.');return}
    if(form.id==='employee-form'){await task(async()=>{const fd=new FormData(form),id=Number(fd.get('id'))||undefined,payload={id,name:fd.get('name'),login:fd.get('login'),role:fd.get('role'),phone:fd.get('phone'),active:fd.get('active')==='on',permissions:fd.getAll('permissions')};if(fd.get('password'))payload.password=fd.get('password');await authApi.employeeSave(payload);await mutate(()=>{},id?'funcionario_editado':'funcionario_criado','employee',id||payload.login,payload.name)},'Funcionário salvo.');return}
    if(form.id==='push-form'){await task(async()=>{const fd=new FormData(form);await pushApi.send({mode:fd.get('mode'),identifier:fd.get('identifier'),title:fd.get('title'),body:fd.get('body'),url:fd.get('url')});await mutate(()=>{},'notificacao_enviada','communication',fd.get('mode'),fd.get('title'))},'Notificação enviada.');return}
    if(form.id==='story-form'){await task(async()=>{const fd=new FormData(form),payload={id:fd.get('id')||undefined,title:fd.get('title'),message:fd.get('message'),mediaType:fd.get('mediaType'),mediaUrl:fd.get('mediaUrl'),actionLabel:fd.get('actionLabel'),actionUrl:fd.get('actionUrl'),audience:fd.get('audience'),planId:Number(fd.get('planId'))||null,city:fd.get('city'),startAt:fd.get('startAt')||'',endAt:fd.get('endAt')||'',active:fd.get('active')==='on'},saved=await storiesApi.save(payload);await mutate(()=>{},payload.id?'publicidade_editada':'publicidade_criada','story',saved?.story?.id||payload.id,payload.title)},'Publicidade salva.');return}
    if(form.id==='efi-form'){await task(async()=>{const fd=new FormData(form),payload={enabled:fd.get('enabled')==='on',environment:fd.get('environment'),pixKey:fd.get('pixKey'),pixAutoReceiverAgency:fd.get('pixAutoReceiverAgency'),pixAutoReceiverAccount:fd.get('pixAutoReceiverAccount'),webhookUrl:fd.get('webhookUrl')};for(const key of ['clientId','clientSecret','certificatePassword'])if(fd.get(key))payload[key]=fd.get(key);const file=fd.get('certificate');if(file&&file.size){payload.certificateName=file.name;payload.certificateBase64=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]||'');reader.onerror=reject;reader.readAsDataURL(file)})}await bankApi.saveEfi(payload);await mutate(()=>{},'integracao_efi_alterada','integration','efi')},'Efí salva.');return}
    if(form.id==='mp-form'){await task(async()=>{const fd=new FormData(form),payload={enabled:fd.get('enabled')==='on',environment:fd.get('environment'),publicKey:fd.get('publicKey')};if(fd.get('accessToken'))payload.accessToken=fd.get('accessToken');await bankApi.saveMercadoPago(payload);if(fd.get('webhookSecret'))await bankApi.saveMercadoPagoWebhook(fd.get('webhookSecret'));await mutate(()=>{},'integracao_mercado_pago_alterada','integration','mercadoPago')},'Mercado Pago salvo.');return}
    if(form.id==='default-bank-form'){await task(async()=>{const fd=new FormData(form);await bankApi.setDefault(fd.get('provider'));await mutate((next)=>{next.banks={...(next.banks||{}),defaultProvider:fd.get('provider')}},'banco_padrao_alterado','integration','default',fd.get('provider'))},'Banco padrão salvo.');return}
    if(form.id==='settings-form'){await task(async()=>{const fd=new FormData(form);await mutate((next)=>{next.settings={...(next.settings||{}),billing_auto_enabled:fd.get('billing_auto_enabled')==='on',billing_auto_days_before:Number(fd.get('billing_auto_days_before'))||7,negotiation_auto_enabled:fd.get('negotiation_auto_enabled')==='on',negotiation_min_overdue_days:Number(fd.get('negotiation_min_overdue_days'))||0,negotiation_cash_discount_percent:Number(fd.get('negotiation_cash_discount_percent'))||0,negotiation_installment_interest_percent:Number(fd.get('negotiation_installment_interest_percent'))||0,negotiation_max_installments:Number(fd.get('negotiation_max_installments'))||3,negotiation_entry_percent:Number(fd.get('negotiation_entry_percent'))||0,negotiation_first_due_days:Number(fd.get('negotiation_first_due_days'))||0,company_name:fd.get('company_name'),cnpj:fd.get('company_cnpj'),ie:fd.get('company_ie'),whatsapp:fd.get('company_whatsapp')};next.company={...(next.company||{}),company_name:fd.get('company_name'),cnpj:fd.get('company_cnpj'),ie:fd.get('company_ie'),whatsapp:fd.get('company_whatsapp')}},'automacoes_alteradas','settings','provider')},'Automações salvas.');return}
  }
  async function showLogin(message=''){root.innerHTML=loginTemplate(configured,message)}
  async function showShell(){const first=NAV.find(([id])=>navAllowed(user,id));if(!navAllowed(user,currentView))currentView=first?.[0]||'dashboard';root.innerHTML=shellTemplate(user);await loadAll();render()}
  root.addEventListener('click',handleClick);root.addEventListener('submit',handleSubmit);
  async function start(){const auth=await authApi.status();configured=auth.configured!==false;if(auth.authenticated&&auth.user){user=auth.user;await showShell()}else await showLogin()}
  return {start};
}
