import {clone,collections,formatBytes,formatRate,invoiceCents,mergedClients,mergedRouters,money,nextId,normalized,openInvoice,text} from './model.js';
import {createForms} from './panel-forms.js';
import {createViews} from './panel-views.js';
import {esc,hasPermission,loginTemplate,moneyToCents,NAV,navAllowed,shellTemplate} from './ui-kit.js';

export function createPanel(root,api){
 const {authApi,stateApi,dataApi,bankApi,mikrotikApi,protocolApi,pushApi,pushOpsApi,storiesApi}=api;
 let configured=true,user=null,state={},stamp='',remoteClients=[],remoteRouters=[],employees=[],protocols=[],bankSafe={},pushStats={},pushOps={},stories=[],storySummary={},view='dashboard',busy=false;
 const clients=()=>mergedClients(state,remoteClients),routers=()=>mergedRouters(state,remoteRouters),data=()=>collections(state);
 const client=id=>clients().find(x=>Number(x.id)===Number(id)),router=id=>routers().find(x=>Number(x.id)===Number(id)),plan=id=>data().plans.find(x=>Number(x.id)===Number(id)),invoice=id=>data().invoices.find(x=>String(x.id)===String(id));
 const ctx=()=>({user,state,clients:clients(),routers:routers(),data:data(),protocols,employees,bankSafe,pushStats,pushOps,stories,storySummary,byClient:client,byRouter:router,byPlan:plan,byInvoice:invoice});
 const now=()=>new Date().toISOString(),role=()=>String(user?.role||'').toLowerCase();
 function toast(msg,kind='success'){const n=document.createElement('div');n.className=`toast ${kind}`;n.textContent=msg;root.querySelector('#toast-root')?.append(n);setTimeout(()=>n.remove(),5000)}
 function modal(title,body,wide=false){const h=root.querySelector('#modal-root');if(h)h.innerHTML=`<div class="modal-backdrop"><section class="modal${wide?' wide':''}"><header><div><span class="section-label">Provedor Plus</span><h3>${esc(title)}</h3></div><button class="modal-x" data-action="close-modal" type="button">×</button></header><div class="modal-body">${body}</div></section></div>`}
 function close(){const h=root.querySelector('#modal-root');if(h)h.innerHTML=''}
 function lock(v){busy=!!v;root.classList.toggle('is-busy',busy);root.querySelectorAll('button:not(.module-tab),input,select,textarea').forEach(el=>{if(v){if(!el.disabled)el.dataset.ppBusy='1';el.disabled=true}else if(el.dataset.ppBusy){el.disabled=false;delete el.dataset.ppBusy}})}
 async function task(fn,msg='Concluído.',keep=false){if(busy)return;lock(true);try{await fn();if(msg)toast(msg);if(!keep)close();await load();render()}catch(e){if(!e?.silent)toast(e.message||String(e),'error')}finally{lock(false)}}
 function audit(next,action,entity,id,detail=''){next.audit=[{id:crypto.randomUUID(),action,entity,entity_id:id??null,description:detail,created_at:now(),created_by_id:user?.id||null,created_by_name:user?.name||user?.email||'Painel'},...(Array.isArray(next.audit)?next.audit:[])].slice(0,1500)}
 async function save(next,action='',entity='',id=null,detail=''){if(action)audit(next,action,entity,id,detail);const r=await stateApi.save(next,stamp);state=r?.state||next;stamp=r?.updated_at||now();return state}
 async function mutate(fn,action='',entity='',id=null,detail=''){const next=clone(state);await fn(next);return save(next,action,entity,id,detail)}
 async function load(){const s=await stateApi.load();state=s?.state&&typeof s.state==='object'?s.state:{};stamp=s?.updated_at||'';const admin=role()==='admin',r=await Promise.allSettled([dataApi.clients(),dataApi.routers(),protocolApi.list(null,200),admin?authApi.employees():[],admin?bankApi.safe():{},admin?pushApi.stats():{},admin?pushOpsApi.get():{},admin?storiesApi.list():{stories:[],summary:{}}]);remoteClients=r[0].status==='fulfilled'?(r[0].value||[]):[];remoteRouters=r[1].status==='fulfilled'?(r[1].value||[]):[];protocols=r[2].status==='fulfilled'?(r[2].value||[]):[];employees=r[3].status==='fulfilled'?(r[3].value||[]):[];bankSafe=r[4].status==='fulfilled'?(r[4].value||{}):{};pushStats=r[5].status==='fulfilled'?(r[5].value||{}):{};pushOps=r[6].status==='fulfilled'?(r[6].value||{}):{};const st=r[7].status==='fulfilled'?(r[7].value||{}):{};stories=st.stories||[];storySummary=st.summary||{}}
 function render(){const host=root.querySelector('#content');if(!host)return;root.querySelector('#page-title').textContent=NAV.find(([id])=>id===view)?.[1]||'Central';root.querySelectorAll('.module-tab').forEach(b=>b.classList.toggle('active',b.dataset.view===view));const v=createViews(ctx());host.innerHTML=(v[view]||v.dashboard)()}
 const forms=()=>createForms(ctx());
 async function secure(r){if(!r)throw Error('MikroTik não encontrado.');const s=await dataApi.routerSecret(r.id);if(!s?.password)throw Error(`Senha segura do MikroTik ${r.name||r.id} não cadastrada.`);return {...r,password:s.password}}
 function putClient(next,row,extra={}){const a=Array.isArray(next.clients)?[...next.clients]:[],i=a.findIndex(x=>Number(x.id)===Number(row.id)),v={...(i>=0?a[i]:{}),...row,...extra};i>=0?a[i]=v:a.push(v);next.clients=a}
 function extras(fd){return {billing_bank_provider:text(fd.get('billing_bank_provider')),notes:text(fd.get('notes')),address_number:text(fd.get('address_number')),neighborhood:text(fd.get('neighborhood')),complement:text(fd.get('complement')),installation_date:text(fd.get('installation_date')),device_ip:text(fd.get('device_ip')),device_port:Number(fd.get('device_port'))||null}}
 async function saveClient(form){const fd=new FormData(form),id=Number(fd.get('id'))||0,old=id?client(id):{},p=plan(fd.get('plan_id')),row={...old,id:id||undefined,name:text(fd.get('name')),document:text(fd.get('document')),contract_number:text(fd.get('contract_number')),email:text(fd.get('email')),phone:text(fd.get('phone')),address:text(fd.get('address')),city:text(fd.get('city')),state:text(fd.get('state')).toUpperCase(),zip_code:text(fd.get('zip_code')),plan_id:Number(fd.get('plan_id'))||null,plan:p?.name||'',due_day:Number(fd.get('due_day'))||10,status:text(fd.get('status'))||'Ativo',router_id:Number(fd.get('router_id'))||null,connection_type:text(fd.get('connection_type')),pppoe_username:text(fd.get('pppoe_username')),pppoe_password:text(fd.get('pppoe_password')),mikrotik_profile:text(fd.get('mikrotik_profile'))||p?.mikrotik_profile||'default',ip:text(fd.get('ip')),mac_address:text(fd.get('mac_address')),auto_block:fd.get('auto_block')==='on',block_after_days:Number(fd.get('block_after_days'))||7};if(!row.name||!row.contract_number)throw Error('Informe nome e contrato.');if(!row.pppoe_password)delete row.pppoe_password;let saved=await dataApi.clientSave(row),net=null,error=null;if(normalized(row.connection_type)==='pppoe'&&row.router_id&&row.pppoe_username){try{if(id&&old?.pppoe_username&&text(old.pppoe_username)!==row.pppoe_username&&!row.pppoe_password)throw Error('Informe a senha PPPoE ao trocar o usuário.');const rt=router(row.router_id),sec=await secure(rt);net=await mikrotikApi.run('pppoe.save',sec,{...row,...saved});if(id&&old?.pppoe_username&&text(old.pppoe_username)!==row.pppoe_username&&old.router_id){await mikrotikApi.run('pppoe.delete',await secure(router(old.router_id)),old)}saved=await dataApi.clientSave({...saved,...row,mikrotik_secret_id:net?.secretId||'',mikrotik_status:'Sincronizado',mikrotik_last_sync:now()})}catch(e){error=e;saved=await dataApi.clientSave({...saved,...row,mikrotik_status:`Falha de sincronização: ${text(e.message).slice(0,160)}`,mikrotik_last_sync:now()})}}
 await mutate(n=>putClient(n,saved,{...extras(fd),plan_id:row.plan_id,plan:row.plan}),id?'cliente_editado':'cliente_criado','client',saved.id,saved.name);if(error)throw Error(`Cliente salvo, mas PPPoE não sincronizado: ${error.message}`)}
 async function saveInvoice(form){const fd=new FormData(form),id=fd.get('id'),old=id?invoice(id):null,cid=Number(fd.get('client_id')),c=client(cid),amount=moneyToCents(fd.get('amount')),discount=moneyToCents(fd.get('discount'));if(!c||!amount||!fd.get('due_date'))throw Error('Informe cliente, vencimento e valor.');if(old&&(old.bank_charge_id||old.bank_payment_id)&&invoiceCents(old)!==amount)throw Error('Cobrança já emitida. Cancele antes de alterar o valor.');const x={...(old||{}),id:old?.id??nextId(data().invoices,state?.seq?.invoices),client_id:cid,due_date:text(fd.get('due_date')),amount_cents:amount,reference:text(fd.get('reference'))||text(fd.get('due_date')).slice(0,7),competency:text(fd.get('reference'))||text(fd.get('due_date')).slice(0,7),billing_type:text(fd.get('billing_type'))||'Mensalidade',description:text(fd.get('description')),bank_provider:text(fd.get('bank_provider'))||old?.bank_provider||'',status:text(fd.get('status'))||'Pendente',created_at:old?.created_at||now(),updated_at:now(),discount_until_due:fd.get('discount_until_due')==='on'&&discount>0,discount_type:discount?'fixed':'',discount_cents:discount,discount_until_date:text(fd.get('due_date')),cashback_eligible:fd.get('cashback_eligible')==='on'};await mutate(n=>{const a=Array.isArray(n.invoices)?[...n.invoices]:[],i=a.findIndex(v=>String(v.id)===String(x.id));i>=0?a[i]=x:a.push(x);n.invoices=a;n.seq={...(n.seq||{}),invoices:Math.max(Number(n.seq?.invoices)||0,Number(x.id)||0)}},old?'mensalidade_editada':'mensalidade_criada','invoice',x.id,`${c.name} · ${money(amount,true)}`)}
 async function bankRun(kind,id){const x=invoice(id),c=client(x?.client_id);if(!x||!c)throw Error('Mensalidade ou cliente não encontrado.');if(kind==='issue'&&(x.bank_charge_id||x.bank_payment_id||x.bank_order_id))throw Error('Cobrança já emitida. Use Sincronizar.');const vault=await bankApi.vault(),provider=x.bank_provider||state?.banks?.defaultProvider||(vault?.efi?.enabled?'efi':vault?.mercadoPago?.enabled?'mercadoPago':'');if(!provider)throw Error('Defina um banco emissor.');const r=await bankApi.proxy({action:kind,provider,invoice:{...x,bank_provider:provider,client_name:c.name,client_contract_number:c.contract_number},client:c,efi:vault?.efi||{},mercadoPago:vault?.mercadoPago||{}});await mutate(n=>{const v=(n.invoices||[]).find(i=>String(i.id)===String(id));if(v){Object.assign(v,r||{},{bank_provider:provider,bank_last_sync_at:now()});if(kind==='sync'&&/paid|pago|settled|approved/i.test(text(r?.bank_status)))Object.assign(v,{status:'Pago',paid_at:r?.paidAt||v.paid_at||now()})}},kind==='issue'?'cobranca_emitida':kind==='sync'?'cobranca_sincronizada':'cobranca_cancelada','invoice',id,c.name)}
 function diag(c,r){return `<div class="diagnostic-panel"><div class="diag-hero ${r.online?'ok':'bad'}"><strong>${r.online?'ONLINE':'OFFLINE'}</strong><span>${esc(c.pppoe_username||'')}</span></div><div class="diag-grid">${[['IP',r.ip||c.ip],['Uptime',r.uptime],['Download',formatRate(r.downloadBps)],['Upload',formatRate(r.uploadBps)],['Baixado',formatBytes(r.downloadBytes)],['Enviado',formatBytes(r.uploadBytes)],['Latência',r.qualityAvailable?`${r.latencyMs} ms`:'—'],['Perda',r.packetLoss==null?'—':`${r.packetLoss}%`],['Perfil',r.profile],['VLAN',r.vlanId||r.vlan],['Porta',r.accessPort||r.accessInterface],['MAC',r.callerId||c.mac_address]].map(([k,v])=>`<article><span>${k}</span><strong>${esc(v||'—')}</strong></article>`).join('')}</div></div>`}
 function details(x){const c=client(x.client_id);return `<div class="detail-grid">${[['Cliente',c?.name||x.client_name_snapshot],['Referência',x.reference||x.id],['Valor',money(invoiceCents(x),true)],['Vencimento',x.due_date],['Status',x.status],['Banco',x.bank_provider]].map(([k,v])=>`<article><span>${k}</span><strong>${esc(v||'—')}</strong></article>`).join('')}</div>${x.bank_pix_code?`<label class="detail-code">PIX<textarea readonly>${esc(x.bank_pix_code)}</textarea></label>`:''}`}
 const perm={'new-client':'clients','edit-client':'clients','delete-client':'clients','client-pppoe':'network','client-connection':'network','client-block':'network','client-unblock':'network','client-invoices':'billing','client-protocols':'tickets','new-plan':'plans','edit-plan':'plans','delete-plan':'plans','new-invoice':'billing','edit-invoice':'billing','invoice-details':'billing','issue-invoice':'billing','sync-invoice':'billing','pay-invoice':'billing','cancel-invoice':'billing','copy-pix':'billing','open-invoice':'billing','cashback-rules':'finance','cashback-adjust':'finance','export-finance':'finance','new-router':'network','edit-router':'network','test-router':'network','sync-router':'network','metrics-router':'network','profiles-router':'network','remote-router':'network','delete-router':'network','new-protocol':'tickets','protocol-details':'tickets','close-protocol':'tickets'};
 const admin=new Set(['new-employee','edit-employee','toggle-employee','new-story','edit-story','toggle-story','delete-story','config-efi','config-mp','test-efi','test-mp','webhooks-efi','scan-push','cancel-push-schedule','use-push-template','delete-push-template','backup-export','backup-import']);
 async function click(e){if(e.target.classList?.contains('modal-backdrop'))return close();const t=e.target.closest('[data-action],[data-view]');if(!t)return;if(t.dataset.view){if(navAllowed(user,t.dataset.view)){view=t.dataset.view;render()}else toast('Sem permissão para esta área.','error');return}const a=t.dataset.action,id=t.dataset.id;if(perm[a]&&!hasPermission(user,perm[a]))return toast('Sem permissão para esta operação.','error');if(admin.has(a)&&role()!=='admin')return toast('Somente administrador.','error');const f=forms();
 if(a==='close-modal')return close();if(a==='refresh')return task(()=>{},'Dados atualizados.');if(a==='logout'){await authApi.logout();user=null;return login()}if(a==='go-invoices'){view='invoices';return render()}
 if(a==='new-client'||a==='edit-client')return modal(id?'Editar cliente':'Novo cliente',f.clientForm(id?client(id):{}),true);
 if(a==='delete-client'){const c=client(id);if(!c||!confirm(`Excluir ${c.name}? O histórico financeiro será preservado.`))return;return task(async()=>{if(normalized(c.connection_type)==='pppoe'&&c.router_id&&c.pppoe_username){if(!hasPermission(user,'network'))throw Error('É necessária permissão de rede para remover o PPPoE.');await mikrotikApi.run('pppoe.delete',await secure(router(c.router_id)),c)}await dataApi.clientDelete(c.id);await mutate(n=>{n.clients=(n.clients||[]).filter(x=>Number(x.id)!==Number(c.id));n.invoices=(n.invoices||[]).map(x=>Number(x.client_id)===Number(c.id)?{...x,client_name_snapshot:c.name}:x)},'cliente_excluido','client',c.id,c.name)},'Cliente e PPPoE removidos.')}
 if(a==='client-pppoe'){const c=client(id),r=router(c?.router_id);if(!c||!r)return toast('Configure o MikroTik e PPPoE do cliente.','error');return task(async()=>{const x=await mikrotikApi.run('pppoe.save',await secure(r),c),saved=await dataApi.clientSave({...c,mikrotik_secret_id:x.secretId||'',mikrotik_status:'Sincronizado',mikrotik_last_sync:now()});await mutate(n=>putClient(n,saved,c),'pppoe_sincronizado','client',c.id,c.pppoe_username)},'PPPoE sincronizado.')}
 if(a==='client-connection'){const c=client(id),r=router(c?.router_id);if(!c||!r)return toast('Cliente sem MikroTik configurado.','error');return task(async()=>{const x=await mikrotikApi.run('client.status',await secure(r),c);try{await dataApi.trafficRecord(c.id,x)}catch{}modal('Diagnóstico da conexão',diag(c,x),true)},'',true)}
 if(a==='client-invoices'){const c=client(id),xs=data().invoices.filter(x=>Number(x.client_id)===Number(id));return modal(`Faturas de ${c?.name||'cliente'}`,xs.length?`<div class="table-wrap"><table><tbody>${xs.map(x=>`<tr><td>${esc(x.reference||x.id)}</td><td>${esc(x.due_date)}</td><td>${money(invoiceCents(x),true)}</td><td>${esc(x.status)}</td><td><button class="btn secondary" data-action="invoice-details" data-id="${esc(x.id)}">Detalhes</button></td></tr>`).join('')}</tbody></table></div>`:'<p class="hint">Sem faturas.</p>',true)}
 if(a==='client-protocols'){const c=client(id);return task(async()=>{const xs=await protocolApi.list(Number(id),100);modal(`Histórico de ${c?.name||'cliente'}`,xs.length?`<div class="timeline-list">${xs.map(x=>`<article><strong>${esc(x.protocol)}</strong><span>${esc(x.subject)} · ${esc(x.status)}</span></article>`).join('')}</div>`:'<p class="hint">Sem protocolos.</p>',true)},'',true)}
 if(a==='client-block'||a==='client-unblock'){const c=client(id),r=router(c?.router_id),block=a==='client-block';if(!c||!r)return toast('Cliente sem MikroTik.','error');if(!confirm(`${block?'Bloquear':'Liberar'} ${c.name}?`))return;return task(async()=>{const x=await mikrotikApi.run(block?'client.block':'client.unblock',await secure(r),c);if(x.verified!==true)throw Error('MikroTik não confirmou a operação.');const saved=await dataApi.clientSave({...c,status:block?'Bloqueado':'Ativo',mikrotik_secret_id:x.secretId||'',mikrotik_status:block?'Bloqueado no MikroTik':'Sincronizado',mikrotik_last_sync:now()});await mutate(n=>putClient(n,saved,c),block?'cliente_bloqueado':'cliente_liberado','client',c.id,c.name)},block?'Cliente bloqueado no MikroTik.':'Cliente liberado no MikroTik.')}
 if(a==='new-plan'||a==='edit-plan')return modal(id?'Editar plano':'Novo plano',f.planForm(id?plan(id):{}));
 if(a==='delete-plan'){const p=plan(id);if(clients().some(c=>Number(c.plan_id)===Number(id)))return toast('Plano em uso. Altere os clientes antes de excluir.','error');if(!confirm(`Excluir ${p?.name||id}?`))return;return task(()=>mutate(n=>{n.plans=(n.plans||[]).filter(x=>Number(x.id)!==Number(id))},'plano_excluido','plan',id,p?.name),'Plano excluído.')}
 if(a==='new-invoice'||a==='edit-invoice')return modal(id?'Editar mensalidade':'Nova mensalidade',f.invoiceForm(id?invoice(id):{}),true);
 if(a==='invoice-details')return modal('Detalhes da cobrança',details(invoice(id)),true);
 if(a==='issue-invoice'||a==='sync-invoice')return task(()=>bankRun(a==='issue-invoice'?'issue':'sync',id),a==='issue-invoice'?'Cobrança emitida.':'Cobrança sincronizada.');
 if(a==='pay-invoice')return modal('Baixa manual',f.manualPaymentForm(invoice(id)));
 if(a==='cancel-invoice'){const x=invoice(id),c=client(x?.client_id);if(!x||!c||!confirm('Cancelar esta cobrança?'))return;return task(async()=>{if(x.bank_charge_id||x.bank_payment_id||x.bank_order_id)await bankRun('cancel',id);await mutate(n=>{const v=(n.invoices||[]).find(i=>String(i.id)===String(id));if(v)v.status='Cancelado'},'mensalidade_cancelada','invoice',id,c.name)},'Cobrança cancelada.')}
 if(a==='copy-pix'){const code=text(invoice(id)?.bank_pix_code);if(!code)return toast('PIX não disponível.','error');await navigator.clipboard.writeText(code);return toast('PIX copiado.')}
 if(a==='open-invoice'){const x=invoice(id),url=text(x?.bank_ticket_url||x?.bank_pdf_url);if(!url)return toast('Link não disponível.','error');window.open(url,'_blank','noopener');return}
 if(a==='cashback-rules')return modal('Regras de cashback',f.cashbackRulesForm());if(a==='cashback-adjust')return modal('Movimentar cashback',f.cashbackAdjustForm());
 if(a==='new-router'||a==='edit-router')return modal(id?'Editar MikroTik':'Novo MikroTik',f.routerForm(id?router(id):{}));
 if(['test-router','sync-router','metrics-router','profiles-router','remote-router'].includes(a)){const r=router(id),map={'test-router':'router.test','sync-router':'router.sync','metrics-router':'router.metrics','profiles-router':'router.profiles','remote-router':'router.remote'};return task(async()=>{const x=await mikrotikApi.run(map[a],await secure(r));if(a==='sync-router')await dataApi.routerSave({...r,last_status:'Conectado',last_sync:now()});modal('Resultado do MikroTik',`<pre class="result-pre">${esc(JSON.stringify(x,null,2))}</pre>`,true)},'',true)}
 if(a==='delete-router'){const r=router(id);if(clients().some(c=>Number(c.router_id)===Number(id)))return toast('MikroTik vinculado a clientes.','error');if(!confirm(`Excluir ${r?.name||id}?`))return;return task(async()=>{await dataApi.routerSecretDelete(id);await dataApi.routerDelete(id);await mutate(n=>{n.routers=(n.routers||[]).filter(x=>Number(x.id)!==Number(id))},'mikrotik_excluido','router',id,r?.name)},'MikroTik excluído.')}
 if(a==='new-protocol')return modal('Abrir chamado',f.protocolForm(),true);if(a==='protocol-details'){const x=protocols.find(p=>p.protocol===id);return modal(`Protocolo ${id}`,`<div class="detail-grid"><article><span>Cliente</span><strong>${esc(client(x?.clientId)?.name||'—')}</strong></article><article><span>Categoria</span><strong>${esc(x?.category||'—')}</strong></article><article><span>Assunto</span><strong>${esc(x?.subject||'—')}</strong></article><article><span>Status</span><strong>${esc(x?.status||'—')}</strong></article></div>`)}if(a==='close-protocol'&&confirm(`Concluir ${id}?`))return task(async()=>{await protocolApi.close(id);await mutate(()=>{},'chamado_concluido','protocol',id,id)},'Chamado concluído.');
 if(a==='new-employee'||a==='edit-employee')return modal(id?'Editar funcionário':'Novo funcionário',f.employeeForm(id?employees.find(x=>Number(x.id)===Number(id)):{}),true);if(a==='toggle-employee'){const x=employees.find(v=>Number(v.id)===Number(id));return task(async()=>{await authApi.employeeToggle(id,x?.active===false);await mutate(()=>{},'funcionario_acesso_alterado','employee',id,x?.name)},'Acesso atualizado.')}
 if(a==='new-story'||a==='edit-story')return modal(id?'Editar publicidade':'Nova publicidade',f.storyForm(id?stories.find(x=>String(x.id)===String(id)):{}),true);if(a==='toggle-story'){const x=stories.find(v=>String(v.id)===String(id));return task(async()=>{await storiesApi.toggle(id,x?.active===false);await mutate(()=>{},'publicidade_alterada','story',id,x?.title)},'Publicidade atualizada.')}if(a==='delete-story'&&confirm('Excluir publicidade?'))return task(async()=>{await storiesApi.remove(id);await mutate(()=>{},'publicidade_excluida','story',id)},'Publicidade excluída.');
 if(a==='config-efi')return modal('Configurar Efí Bank',f.efiForm(),true);if(a==='config-mp')return modal('Configurar Mercado Pago',f.mpForm(),true);if(a==='test-efi')return task(()=>bankApi.testEfi(),'Conexão Efí confirmada.');if(a==='test-mp')return task(()=>bankApi.testMercadoPago(),'Conexão Mercado Pago confirmada.');if(a==='webhooks-efi')return task(()=>bankApi.configureEfiWebhooks(),'Webhooks Efí configurados.');
 if(a==='scan-push')return task(()=>pushOpsApi.scanNow(),'Verificação de notificações concluída.');if(a==='cancel-push-schedule')return task(()=>pushOpsApi.cancelSchedule(Number(id)),'Agendamento cancelado.');if(a==='delete-push-template')return task(()=>pushOpsApi.deleteTemplate(id),'Modelo excluído.');if(a==='use-push-template'){const x=(pushOps.templates||[]).find(v=>v.id===id),form=root.querySelector('#push-form');if(x&&form){form.elements.title.value=x.title;form.elements.body.value=x.body;form.elements.url.value=x.url||'/';form.scrollIntoView({behavior:'smooth'})}return}
 if(a==='export-finance'){const rows=[['ID','Cliente','Referência','Vencimento','Valor','Status','Forma','Pago em'],...data().invoices.map(x=>[x.id,client(x.client_id)?.name||x.client_name_snapshot||'',x.reference||'',x.due_date||'',(invoiceCents(x)/100).toFixed(2),x.status||'',x.payment_method||'',x.paid_at||''])],csv=rows.map(r=>r.map(v=>`"${String(v??'').replace(/"/g,'""')}"`).join(';')).join('\n'),url=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv'})),d=document.createElement('a');d.href=url;d.download=`provedor-plus-financeiro-${now().slice(0,10)}.csv`;d.click();setTimeout(()=>URL.revokeObjectURL(url),500);return}
 if(a==='backup-export'){const payload={format:'provedor-plus-backup-v1',createdAt:now(),state:clone(state),clients:clients(),routers:routers().map(({password,...r})=>r)},url=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'})),d=document.createElement('a');d.href=url;d.download=`provedor-plus-backup-${now().slice(0,10)}.json`;d.click();setTimeout(()=>URL.revokeObjectURL(url),500);return toast('Backup exportado.')}
 if(a==='backup-import'){const input=document.createElement('input');input.type='file';input.accept='.json';input.onchange=async()=>{try{const file=input.files?.[0];if(!file)return;const p=JSON.parse(await file.text());if(p.format!=='provedor-plus-backup-v1'||!p.state)throw Error('Backup inválido.');if(!confirm('Restaurar este backup?'))return;await task(async()=>{for(const c of p.clients||[])await dataApi.clientSave(c);for(const r of p.routers||[])if(r.id&&r.host&&r.username)await dataApi.routerSave(r);const restored=clone(p.state);audit(restored,'backup_restaurado','backup','state',file.name);const s=await stateApi.save(restored,stamp);state=s?.state||restored;stamp=s?.updated_at||now()},'Backup restaurado.')}catch(err){toast(err.message,'error')}};input.click();return}
 }
 async function submit(e){const form=e.target.closest('form');if(!form)return;e.preventDefault();if(form.id==='login-form'){const fd=new FormData(form),err=form.querySelector('#login-error');try{const r=configured?await authApi.login(fd.get('login'),fd.get('password')):await authApi.setup(fd.get('name'),fd.get('login'),fd.get('password'));user=r.user;await shell()}catch(x){err.textContent=x.message}return}
 if(form.id==='client-form')return task(()=>saveClient(form),'Cliente salvo e PPPoE sincronizado.');if(form.id==='invoice-form')return task(()=>saveInvoice(form),'Mensalidade salva.');
 if(form.id==='plan-form')return task(async()=>{const fd=new FormData(form),id=Number(fd.get('id'))||nextId(data().plans,state?.seq?.plans),old=plan(id),x={...(old||{}),id,name:text(fd.get('name')),speed:text(fd.get('speed')),price_cents:moneyToCents(fd.get('price')),installation_fee_cents:moneyToCents(fd.get('installation_fee')),mikrotik_profile:text(fd.get('mikrotik_profile'))||'default',download_mbps:Number(fd.get('download_mbps'))||0,upload_mbps:Number(fd.get('upload_mbps'))||0,active:fd.get('active')==='on',portal_visible:fd.get('portal_visible')==='on',highlighted:fd.get('highlighted')==='on',description:text(fd.get('description')),updated_at:now()};if(!x.name||!x.price_cents)throw Error('Informe nome e valor do plano.');await mutate(n=>{const a=Array.isArray(n.plans)?[...n.plans]:[],i=a.findIndex(v=>Number(v.id)===id);i>=0?a[i]=x:a.push(x);n.plans=a;n.seq={...(n.seq||{}),plans:Math.max(Number(n.seq?.plans)||0,id)}},old?'plano_editado':'plano_criado','plan',id,x.name)},'Plano salvo.');
 if(form.id==='manual-payment-form')return task(async()=>{const fd=new FormData(form),x=invoice(fd.get('id')),c=client(x?.client_id);if(!x||!c)throw Error('Mensalidade não encontrada.');if(x.bank_charge_id||x.bank_payment_id||x.bank_order_id)await bankRun('cancel',x.id);await mutate(n=>{const v=(n.invoices||[]).find(i=>String(i.id)===String(x.id));if(v)Object.assign(v,{status:'Pago',payment_method:text(fd.get('payment_method'))||'Baixa manual',paid_by:user?.name||'Painel',paid_at:new Date(fd.get('paid_at')).toISOString(),payment_note:text(fd.get('payment_note')),payment_origin:'manual'})},'mensalidade_baixada','invoice',x.id,c.name)},'Baixa registrada.');
 if(form.id==='cashback-rules-form')return task(async()=>{const fd=new FormData(form);await mutate(n=>{n.settings={...(n.settings||{}),cashback_enabled:fd.get('cashback_enabled')==='on',cashback_mode:fd.get('cashback_mode')==='fixed'?'fixed':'percent',cashback_rate:Math.max(0,Math.min(100,Number(fd.get('cashback_rate'))||0)),cashback_fixed_cents:moneyToCents(fd.get('cashback_fixed'))}},'cashback_regras_alteradas','settings','cashback')},'Regras de cashback salvas.');
 if(form.id==='cashback-adjust-form')return task(async()=>{const fd=new FormData(form);await dataApi.cashbackAdjust({clientId:Number(fd.get('client_id')),operation:fd.get('operation'),amount_cents:moneyToCents(fd.get('amount')),reason:fd.get('reason')})},'Carteira atualizada.');
 if(form.id==='router-form')return task(async()=>{const fd=new FormData(form),id=Number(fd.get('id'))||undefined,old=id?router(id):{},x={...old,id,name:text(fd.get('name')),host:text(fd.get('host')),port:Number(fd.get('port'))||443,username:text(fd.get('username')),active:fd.get('active')==='on',allow_self_signed:fd.get('allow_self_signed')==='on'},pass=text(fd.get('password'));let saved;if(pass){const test=await mikrotikApi.run('router.test',{...x,password:pass});saved=await dataApi.routerSave({...x,last_status:test?.connected?'Conectado':'Ativo',last_sync:now()});await dataApi.routerSecretSave(saved.id,pass)}else saved=await dataApi.routerSave(x);await mutate(n=>{const a=Array.isArray(n.routers)?[...n.routers]:[],i=a.findIndex(v=>Number(v.id)===Number(saved.id));i>=0?a[i]={...a[i],...saved}:a.push(saved);n.routers=a},id?'mikrotik_editado':'mikrotik_criado','router',saved.id,saved.name)},'MikroTik salvo.');
 if(form.id==='protocol-form')return task(async()=>{const fd=new FormData(form),details={description:text(fd.get('details')),priority:text(fd.get('priority'))||'Normal',assigned_user_id:Number(fd.get('assigned_user_id'))||null,assigned_name:employees.find(x=>Number(x.id)===Number(fd.get('assigned_user_id')))?.name||'',scheduled_at:text(fd.get('scheduled_at'))},x=await protocolApi.create({clientId:Number(fd.get('clientId'))||null,category:fd.get('category'),subject:fd.get('subject'),status:fd.get('status'),details});await mutate(()=>{},'chamado_aberto','protocol',x.protocol,`${fd.get('subject')} · ${details.priority}`)},'Chamado aberto.');
 if(form.id==='employee-form')return task(async()=>{const fd=new FormData(form),id=Number(fd.get('id'))||undefined,x={id,name:fd.get('name'),login:fd.get('login'),role:fd.get('role'),phone:fd.get('phone'),active:fd.get('active')==='on',permissions:fd.getAll('permissions')};if(fd.get('password'))x.password=fd.get('password');await authApi.employeeSave(x);await mutate(()=>{},id?'funcionario_editado':'funcionario_criado','employee',id||x.login,x.name)},'Funcionário salvo.');
 if(form.id==='push-form')return task(async()=>{const fd=new FormData(form),x={mode:fd.get('mode'),identifier:fd.get('identifier'),title:fd.get('title'),body:fd.get('body'),url:fd.get('url')};if(fd.get('schedule_enabled')==='on'){const d=new Date(fd.get('scheduled_for'));if(Number.isNaN(d.getTime())||d<=new Date())throw Error('Escolha data/hora futura.');await pushOpsApi.schedule({...x,scheduledFor:d.toISOString()})}else await pushApi.send(x);await mutate(()=>{},fd.get('schedule_enabled')==='on'?'notificacao_agendada':'notificacao_enviada','communication',x.mode,x.title)},form.elements.schedule_enabled.checked?'Notificação agendada.':'Notificação enviada.');
 if(form.id==='push-settings-form')return task(async()=>{const fd=new FormData(form),x={};for(const k of ['statusSuspended','statusRestored','trustRelease','dueChange','negotiation','protocols','planChange'])x[k]=fd.get(k)==='on';await pushOpsApi.save(x);await mutate(()=>{},'notificacoes_automaticas_alteradas','communication','push')},'Automações salvas.');
 if(form.id==='push-template-form')return task(async()=>{const fd=new FormData(form);await pushOpsApi.saveTemplate({name:fd.get('name'),title:fd.get('title'),body:fd.get('body'),url:fd.get('url')});await mutate(()=>{},'modelo_notificacao_criado','communication','template',fd.get('name'))},'Modelo salvo.');
 if(form.id==='story-form')return task(async()=>{const fd=new FormData(form),x={id:fd.get('id')||undefined,title:fd.get('title'),message:fd.get('message'),mediaType:fd.get('mediaType'),mediaUrl:fd.get('mediaUrl'),actionLabel:fd.get('actionLabel'),actionUrl:fd.get('actionUrl'),audience:fd.get('audience'),planId:Number(fd.get('planId'))||null,city:fd.get('city'),startAt:fd.get('startAt')||'',endAt:fd.get('endAt')||'',active:fd.get('active')==='on'},s=await storiesApi.save(x);await mutate(()=>{},x.id?'publicidade_editada':'publicidade_criada','story',s?.story?.id||x.id,x.title)},'Publicidade salva.');
 if(form.id==='efi-form')return task(async()=>{const fd=new FormData(form),x={enabled:fd.get('enabled')==='on',environment:fd.get('environment'),pixKey:fd.get('pixKey'),pixAutoReceiverAgency:fd.get('pixAutoReceiverAgency'),pixAutoReceiverAccount:fd.get('pixAutoReceiverAccount'),webhookUrl:fd.get('webhookUrl')};for(const k of ['clientId','clientSecret','certificatePassword'])if(fd.get(k))x[k]=fd.get(k);const file=fd.get('certificate');if(file?.size){x.certificateName=file.name;x.certificateBase64=await new Promise((ok,no)=>{const r=new FileReader();r.onload=()=>ok(String(r.result).split(',')[1]||'');r.onerror=no;r.readAsDataURL(file)})}await bankApi.saveEfi(x);await mutate(()=>{},'integracao_efi_alterada','integration','efi')},'Efí salva.');
 if(form.id==='mp-form')return task(async()=>{const fd=new FormData(form),x={enabled:fd.get('enabled')==='on',environment:fd.get('environment'),publicKey:fd.get('publicKey')};if(fd.get('accessToken'))x.accessToken=fd.get('accessToken');await bankApi.saveMercadoPago(x);if(fd.get('webhookSecret'))await bankApi.saveMercadoPagoWebhook(fd.get('webhookSecret'));await mutate(()=>{},'integracao_mercado_pago_alterada','integration','mercadoPago')},'Mercado Pago salvo.');
 if(form.id==='default-bank-form')return task(async()=>{const fd=new FormData(form);await bankApi.setDefault(fd.get('provider'));await mutate(n=>{n.banks={...(n.banks||{}),defaultProvider:fd.get('provider')}},'banco_padrao_alterado','integration','default',fd.get('provider'))},'Banco padrão salvo.');
 if(form.id==='settings-form')return task(async()=>{const fd=new FormData(form);await mutate(n=>{n.settings={...(n.settings||{}),billing_auto_enabled:fd.get('billing_auto_enabled')==='on',billing_auto_days_before:Number(fd.get('billing_auto_days_before'))||7,negotiation_auto_enabled:fd.get('negotiation_auto_enabled')==='on',negotiation_min_overdue_days:Number(fd.get('negotiation_min_overdue_days'))||0,negotiation_cash_discount_percent:Number(fd.get('negotiation_cash_discount_percent'))||0,negotiation_installment_interest_percent:Number(fd.get('negotiation_installment_interest_percent'))||0,negotiation_max_installments:Number(fd.get('negotiation_max_installments'))||3,negotiation_entry_percent:Number(fd.get('negotiation_entry_percent'))||0,negotiation_first_due_days:Number(fd.get('negotiation_first_due_days'))||0,company_name:fd.get('company_name'),cnpj:fd.get('company_cnpj'),ie:fd.get('company_ie'),whatsapp:fd.get('company_whatsapp')};n.company={...(n.company||{}),company_name:fd.get('company_name'),cnpj:fd.get('company_cnpj'),ie:fd.get('company_ie'),whatsapp:fd.get('company_whatsapp')}},'automacoes_alteradas','settings','provider')},'Automações salvas.');
 }
 async function login(msg=''){root.innerHTML=loginTemplate(configured,msg)}async function shell(){const first=NAV.find(([id])=>navAllowed(user,id));if(!navAllowed(user,view))view=first?.[0]||'dashboard';root.innerHTML=shellTemplate(user);await load();render()}root.addEventListener('click',click);root.addEventListener('submit',submit);async function start(){const a=await authApi.status();configured=a.configured!==false;if(a.authenticated&&a.user){user=a.user;await shell()}else await login()}return {start};
}
